from __future__ import annotations

import hashlib
from typing import TYPE_CHECKING

from retro_data_structures.disc import game_disc
from retro_data_structures.disc.gc_disc import GcDisc

if TYPE_CHECKING:
    from pathlib import Path


def test_prime1_dol(prime1_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime1_iso)
    disc_dol = disc.get_dol()

    assert hashlib.sha256(disc_dol).digest() == (
        b"wz\x83\n8\xa1\xd2\x07\x11i\x85g\xff\x89X\xfbO\xe7$\x1ar?J\x18\xe25YP\xd7\x9f\xc8V"
    )


def test_prime1_files(prime1_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime1_iso)
    files = disc.files()

    assert files == [
        "opening.bnr",
        "client_pad.bin",
        "NESemu.rel",
        "NESemuD.rel",
        "NESemuP.rel",
        "default.dol",
        "SlideShow.PAK",
        "Tweaks.Pak",
        "MiscData.pak",
        "SamusGun.pak",
        "TestAnim.Pak",
        "SamGunFx.pak",
        "MidiData.pak",
        "GGuiSys.pak",
        "Metroid8.pak",
        "Metroid1.pak",
        "NoARAM.pak",
        "AudioGrp.pak",
        "Metroid7.pak",
        "metroid5.pak",
        "Metroid4.pak",
        "Metroid6.pak",
        "Metroid3.pak",
        "Metroid2.pak",
        "Video/00_first_start.thp",
        "Video/01_startloop.thp",
        "Video/02_start_fileselect_A.thp",
        "Video/02_start_fileselect_B.thp",
        "Video/02_start_fileselect_C.thp",
        "Video/03_fileselectloop.thp",
        "Video/04_fileselect_playgame_A.thp",
        "Video/04_fileselect_playgame_B.thp",
        "Video/04_fileselect_playgame_C.thp",
        "Video/05_tallonText.thp",
        "Video/06_fileselect_GBA.thp",
        "Video/07_GBAloop.thp",
        "Video/08_GBA_fileselect.thp",
        "Video/AfterCredits.thp",
        "Video/attract0.thp",
        "Video/attract1.thp",
        "Video/attract2.thp",
        "Video/attract3.thp",
        "Video/attract4.thp",
        "Video/attract5.thp",
        "Video/attract6.thp",
        "Video/attract7.thp",
        "Video/attract8.thp",
        "Video/attract9.thp",
        "Video/creditBG.thp",
        "Video/from_gallery.thp",
        "Video/losegame.thp",
        "Video/SpecialEnding.thp",
        "Video/to_gallery.thp",
        "Video/win_bad_begin.thp",
        "Video/win_bad_end.thp",
        "Video/win_bad_loop.thp",
        "Video/win_good_begin.thp",
        "Video/win_good_end.thp",
        "Video/win_good_loop.thp",
        "Audio/amb_x_elevator_lp_02.dsp",
        "Audio/crash-ship-3L.dsp",
        "Audio/crash-ship-3R.dsp",
        "Audio/crash-ship-maeL.dsp",
        "Audio/crash-ship-maeR.dsp",
        "Audio/CraterReveal2.dsp",
        "Audio/cra_mainL.dsp",
        "Audio/cra_mainR.dsp",
        "Audio/cra_mprime1L.dsp",
        "Audio/cra_mprime1R.dsp",
        "Audio/cra_mprime2L.dsp",
        "Audio/cra_mprime2R.dsp",
        "Audio/END-escapeL.dsp",
        "Audio/END-escapeR.dsp",
        "Audio/ending3.rsf",
        "Audio/evt_x_event_00.dsp",
        "Audio/frontend_1.rsf",
        "Audio/frontend_2.rsf",
        "Audio/gen_elevatorL.dsp",
        "Audio/gen_elevatorR.dsp",
        "Audio/gen_puzzleL.dsp",
        "Audio/gen_puzzleR.dsp",
        "Audio/gen_rechargeL.dsp",
        "Audio/gen_rechargeR.dsp",
        "Audio/gen_SaveStationL.dsp",
        "Audio/gen_SaveStationR.dsp",
        "Audio/gen_ShortBattle2L.dsp",
        "Audio/gen_ShortBattle2R.dsp",
        "Audio/gen_ShortBattleL.dsp",
        "Audio/gen_ShortBattleR.dsp",
        "Audio/ice_chapelL.dsp",
        "Audio/ice_chapelR.dsp",
        "Audio/ice_connectL.dsp",
        "Audio/ice_connectR.dsp",
        "Audio/ice_kincyoL.dsp",
        "Audio/ice_kincyoR.dsp",
        "Audio/ice_shorelinesL.dsp",
        "Audio/ice_shorelinesR.dsp",
        "Audio/ice_thardusL.dsp",
        "Audio/ice_thardusR.dsp",
        "Audio/ice_worldmainL.dsp",
        "Audio/ice_worldmainR.dsp",
        "Audio/ice_x_wind_lp_00L.dsp",
        "Audio/ice_x_wind_lp_00R.dsp",
        "Audio/int_biohazardL.dsp",
        "Audio/int_biohazardR.dsp",
        "Audio/int_escapel.dsp",
        "Audio/int_escaper.dsp",
        "Audio/int_introcinemaL.dsp",
        "Audio/int_introcinemaR.dsp",
        "Audio/int_introstageL.dsp",
        "Audio/int_introstageR.dsp",
        "Audio/int_parasitequeenL.dsp",
        "Audio/int_parasitequeenR.dsp",
        "Audio/int_spaceL.dsp",
        "Audio/int_spaceR.dsp",
        "Audio/int_toujouL.dsp",
        "Audio/int_toujouR.dsp",
        "Audio/itm_x_short_02.dsp",
        "Audio/jin_artifact.dsp",
        "Audio/jin_itemattain.dsp",
        "Audio/lav_lavamaeL.dsp",
        "Audio/lav_lavamaeR.dsp",
        "Audio/lav_lavamainL.dsp",
        "Audio/lav_lavamainR.dsp",
        "Audio/min_darkL.dsp",
        "Audio/min_darkR.dsp",
        "Audio/min_mainL.dsp",
        "Audio/min_mainR.dsp",
        "Audio/min_omegapirateL.dsp",
        "Audio/min_omegapirateR.dsp",
        "Audio/min_phazonL.dsp",
        "Audio/min_phazonR.dsp",
        "Audio/min_x_wind_lp_01L.dsp",
        "Audio/min_x_wind_lp_01R.dsp",
        "Audio/over-craterrevealL.dsp",
        "Audio/over-craterrevealR.dsp",
        "Audio/over-ridleydeathL.dsp",
        "Audio/over-ridleydeathR.dsp",
        "Audio/over-ridleyL.dsp",
        "Audio/over-ridleyR.dsp",
        "Audio/over-stonehengeL.dsp",
        "Audio/over-stonehengeR.dsp",
        "Audio/over-world-daichiL.dsp",
        "Audio/over-world-daichiR.dsp",
        "Audio/over-worldL.dsp",
        "Audio/over-worldR.dsp",
        "Audio/pir_battle3L.dsp",
        "Audio/pir_battle3R.dsp",
        "Audio/pir_isogiL.dsp",
        "Audio/pir_isogiR.dsp",
        "Audio/pir_yoinL.dsp",
        "Audio/pir_yoinR.dsp",
        "Audio/pir_zencyoL.dsp",
        "Audio/pir_zencyoR.dsp",
        "Audio/pvm01.dsp",
        "Audio/rid_r_death_01.dsp",
        "Audio/ruins-firstL.dsp",
        "Audio/ruins-firstR.dsp",
        "Audio/ruins-nakaL.dsp",
        "Audio/ruins-nakaR.dsp",
        "Audio/Ruins-soto-AL.dsp",
        "Audio/Ruins-soto-AR.dsp",
        "Audio/Ruins-soto-BL.dsp",
        "Audio/Ruins-soto-BR.dsp",
        "Audio/rui_chozobowlingL.dsp",
        "Audio/rui_chozobowlingR.dsp",
        "Audio/rui_flaaghraL.dsp",
        "Audio/rui_flaaghraR.dsp",
        "Audio/rui_hivetotemL.dsp",
        "Audio/rui_hivetotemR.dsp",
        "Audio/rui_monkeylowerL.dsp",
        "Audio/rui_monkeylowerR.dsp",
        "Audio/rui_samusL.dsp",
        "Audio/rui_samusR.dsp",
        "Audio/samusjak.rsf",
        "Audio/sam_samusappear.dsp",
        "Audio/tha_b_enraged_00.dsp",
        "Audio/tha_r_death_00.dsp",
    ]


def test_prime2_dol(prime2_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime2_iso)
    disc_dol = disc.get_dol()

    assert hashlib.sha256(disc_dol).digest() == (
        b"v!\xe7W\x1e\x0e\xe4\xe0\x98\xa4\x0b\xc8\xa0\xa3dx\x11\xbd\x94NC\x02R)Bl}\xea\xe1v\x06\x84"
    )


def test_prime2_files(prime2_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime2_iso)
    files = disc.files()

    assert files == [
        "opening.bnr",
        "FrontEnd.pak",
        "default.dol",
        "GGuiSys.pak",
        "LogBook.pak",
        "MidiData.pak",
        "MiscData.pak",
        "SamGunFx.pak",
        "SamGunFxLow.pak",
        "SamGunFxMulti.pak",
        "SamusGun.pak",
        "SamusGunLow.pak",
        "TestAnim.pak",
        "SlideShow.pak",
        "Standard.ntwk",
        "Metroid6.pak",
        "AudioGrp.pak",
        "NoARAM.pak",
        "Metroid2.pak",
        "Metroid5.pak",
        "Metroid4.pak",
        "Metroid3.pak",
        "Metroid1.pak",
        "Video/Intro_to_Logo.thp",
        "Video/Logo_Loop.thp",
        "Video/Background_Loop.thp",
        "Video/Multiplayer_Loop.thp",
        "Video/Background_Outro.thp",
        "Video/Credits_Loop.thp",
        "Video/Death_Movie.thp",
        "Video/Multiplayer_Outro.thp",
        "Video/Outro_to_Background.thp",
        "Video/Win_Movie_begin.thp",
        "Video/Win_Movie_end.thp",
        "Video/Win_Movie_loop.thp",
        "Video/Attract02_32.thp",
        "Video/Attract03_32.thp",
        "Video/Attract08_31.thp",
        "Video/Attract09_31.thp",
        "Video/Attract07_31.thp",
        "Video/Attract06_31.thp",
        "Video/openPartOne.thp",
        "Video/lastStandFlashback.thp",
        "Video/gameEnding_PlanetAether.thp",
        "Audio/after-credit-32.dsp",
        "Audio/boss-go32.dsp",
        "Audio/Clif-dark32.dsp",
        "Audio/Cliff-Bos2-32.dsp",
        "Audio/DarkSamus.dsp",
        "Audio/Cliff-vocal32.dsp",
        "Audio/cliff2-1-32.dsp",
        "Audio/Dark-Swamp-32.dsp",
        "Audio/Dark-Temple32.dsp",
        "Audio/darksamus-mae.dsp",
        "Audio/DarkWorld_sand.dsp",
        "Audio/DS-appears2-32.dsp",
        "Audio/echoes-end1-32.dsp",
        "Audio/echoes-select2-32.dsp",
        "Audio/DSP.txt",
        "Audio/ele32.dsp",
        "Audio/heishi32.dsp",
        "Audio/Ending-part2-1_32.dsp",
        "Audio/Ending-part1-32.dsp",
        "Audio/Ending-part2-3_32.dsp",
        "Audio/Ending-part2-3_SFX.dsp",
        "Audio/Ending-part2-1_SFX.dsp",
        "Audio/Ending-part2B-75-32_edit.dsp",
        "Audio/Ending-part3-3-SFX1.dsp",
        "Audio/Ending-part3-3-SFX2.dsp",
        "Audio/ending-part3-3-32.dsp",
        "Audio/Enp-ing-type1-3-32.dsp",
        "Audio/Enp-ing-type2-3-32.dsp",
        "Audio/escape3-1a-32.dsp",
        "Audio/evt_x_event_00.dsp",
        "Audio/ing_Large.dsp",
        "Audio/intro-toujou.dsp",
        "Audio/itm_x_long_00.dsp",
        "Audio/itm_x_short_00.dsp",
        "Audio/last-sta3-1-32edit.dsp",
        "Audio/lum_x_voxholo_00.dsp",
        "Audio/lum_x_voxholo_01.dsp",
        "Audio/lum_x_voxholo_02.dsp",
        "Audio/lum_x_voxholo_03.dsp",
        "Audio/lum_x_voxholo_04.dsp",
        "Audio/lum_x_voxholo_05.dsp",
        "Audio/lum_x_voxholo_06.dsp",
        "Audio/lum_x_voxholo_07.dsp",
        "Audio/lum_x_vox_00.dsp",
        "Audio/lum_x_vox_01.dsp",
        "Audio/lum_x_vox_02.dsp",
        "Audio/lum_x_vox_03.dsp",
        "Audio/lum_x_vox_04.dsp",
        "Audio/lum_x_vox_05.dsp",
        "Audio/lum_x_vox_06.dsp",
        "Audio/lum_x_vox_07.dsp",
        "Audio/Moth-Temple-intro32.dsp",
        "Audio/Moth-Temple-jin32.dsp",
        "Audio/Moth-Temple-open32-2.dsp",
        "Audio/mp-puzzle.dsp",
        "Audio/multi-defbgm-speed-doon32.dsp",
        "Audio/multi-defbgm-speed-loop32.dsp",
        "Audio/multi-defbgm32.dsp",
        "Audio/multiplay9-32-3.dsp",
        "Audio/opening-cine3-2.dsp",
        "Audio/pirates_ato.dsp",
        "Audio/pirates_kyu-3-32.dsp",
        "Audio/pirates_zencyo.dsp",
        "Audio/Ruminas-after2-32.dsp",
        "Audio/RUMINAS-short32.dsp",
        "Audio/RUMINAS-TAME2-32.dsp",
        "Audio/samusjak_edit.dsp",
        "Audio/sand_soto.dsp",
        "Audio/Ruminas-tuuro32.dsp",
        "Audio/sand-boss32.dsp",
        "Audio/savestation.dsp",
        "Audio/short-Bat-32.dsp",
        "Audio/skytenkey-jin-short32.dsp",
        "Audio/skytenkey-jin32.dsp",
        "Audio/SplinterHive-132.dsp",
        "Audio/SplinterHive-naka32.dsp",
        "Audio/sunG-heya-dark32.dsp",
        "Audio/sunG-heya32.dsp",
        "Audio/swamp3-32.dsp",
        "Audio/swanp-boss-type1-32.dsp",
        "Audio/swanp-boss-type2-32.dsp",
        "Audio/swanp-chika-dark32.dsp",
        "Audio/swanp-chika32.dsp",
        "Audio/swanp-mae32.dsp",
        "Audio/zonbihei32-2.dsp",
        "RelProd/AIMannedTurret.rel",
        "RelProd/AtomicAlpha.rel",
        "RelProd/AtomicBeta.rel",
        "RelProd/BacteriaSwarm.rel",
        "RelProd/Blogg.rel",
        "RelProd/ChozoGhost.rel",
        "RelProd/CommandoPirate.rel",
        "RelProd/DarkCommando.rel",
        "RelProd/DarkSamus.rel",
        "RelProd/DarkSamusBattleStage.rel",
        "RelProd/DarkTrooper.rel",
        "RelProd/DestructibleBarrier.rel",
        "RelProd/DigitalGuardian.rel",
        "RelProd/ElitePirate.rel",
        "RelProd/EmperorIngStage1.rel",
        "RelProd/EmperorIngStage2Tentacle.rel",
        "RelProd/EmperorIngStage3.rel",
        "RelProd/EyeBall.rel",
        "RelProd/FishCloud.rel",
        "RelProd/FlyerSwarm.rel",
        "RelProd/FlyingPirate.rel",
        "RelProd/FogOverlay.rel",
        "RelProd/ForgottenObject.rel",
        "RelProd/GeomBlobV2.rel",
        "RelProd/Glowbug.rel",
        "RelProd/Grenchler.rel",
        "RelProd/GunTurret.rel",
        "RelProd/Ing.rel",
        "RelProd/IngBlobSwarm.rel",
        "RelProd/IngBoostBallGuardian.rel",
        "RelProd/IngPuddle.rel",
        "RelProd/IngSnatchingSwarm.rel",
        "RelProd/IngSpaceJumpGuardian.rel",
        "RelProd/IngSpiderballGuardian.rel",
        "RelProd/IngSwarm.rel",
        "RelProd/Kralee.rel",
        "RelProd/Krocuss.rel",
        "RelProd/Lumite.rel",
        "RelProd/MediumIng.rel",
        "RelProd/Metaree.rel",
        "RelProd/MetareeSwarm.rel",
        "RelProd/Metroid.rel",
        "RelProd/MinorIng.rel",
        "RelProd/MysteryFlyer.rel",
        "RelProd/OctapedeSegment.rel",
        "RelProd/Parasite.rel",
        "RelProd/PillBug.rel",
        "RelProd/PirateRagDoll.rel",
        "RelProd/PlantScarabSwarm.rel",
        "RelProd/PuddleSpore.rel",
        "RelProd/Puffer.rel",
        "RelProd/Rezbit.rel",
        "RelProd/Ripper.rel",
        "RelProd/RubiksPuzzle.rel",
        "RelProd/SandBoss.rel",
        "RelProd/Sandworm.rel",
        "RelProd/ScriptCannonBall.rel",
        "RelProd/ScriptCoin.rel",
        "RelProd/ScriptFrontEndDataNetwork.rel",
        "RelProd/ScriptGui.rel",
        "RelProd/ScriptPlayerActor.rel",
        "RelProd/ScriptPlayerProxy.rel",
        "RelProd/ScriptPlayerTurret.rel",
        "RelProd/ScriptRiftPortal.rel",
        "RelProd/ScriptRsfAudio.rel",
        "RelProd/ScriptSafeZone.rel",
        "RelProd/ScriptStreamedMovie.rel",
        "RelProd/Shredder.rel",
        "RelProd/Shrieker.rel",
        "RelProd/SkyRipple.rel",
        "RelProd/SnakeWeedSwarm.rel",
        "RelProd/SpacePirate.rel",
        "RelProd/SpankWeed.rel",
        "RelProd/Splinter.rel",
        "RelProd/Splitter.rel",
        "RelProd/Sporb.rel",
        "RelProd/StoneToad.rel",
        "RelProd/SwampBossStage1.rel",
        "RelProd/SwampBossStage2.rel",
        "RelProd/SwarmBasics.rel",
        "RelProd/Tryclops.rel",
        "RelProd/Tweaks.rel",
        "RelProd/WallCrawler.rel",
        "RelProd/WallCrawlerSwarm.rel",
        "RelProd/WallWalker.rel",
        "RelProd/WispTentacle.rel",
    ]


def test_prime3_dol(prime3_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime3_iso)
    disc_dol = disc.get_dol()

    assert hashlib.sha256(disc_dol).digest() == (
        b'kU\x0f"\x16\x02\x07GG\xa2\xe6\x1b\n\xa0d ?\xd4\x93\xf6\x86]\xfb;\x1a\x91&\x82\x06^a\x04'
    )


def test_prime1_file_tree_roundtrip(prime1_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime1_iso)
    fst = disc._raw.data_partition.fst
    original_tree = game_disc.decode_into_file_tree(fst)
    encoded_fst = game_disc.encode_from_file_tree(original_tree)
    assert game_disc.decode_into_file_tree(encoded_fst) == original_tree


def test_prime2_file_tree_roundtrip(prime2_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime2_iso)
    fst = disc._raw.data_partition.fst
    original_tree = game_disc.decode_into_file_tree(fst)
    encoded_fst = game_disc.encode_from_file_tree(original_tree)
    assert game_disc.decode_into_file_tree(encoded_fst) == original_tree


def test_prime2_build(prime2_iso: Path) -> None:
    disc = game_disc.GameDisc.parse(prime2_iso)
    raw = prime2_iso.read_bytes()

    encoded = GcDisc.build(disc._raw)
    raw_part = raw[: len(encoded)]

    assert encoded == raw_part
