# Generated File
# ruff: noqa: I001
from __future__ import annotations
import functools
import typing

from retro_data_structures.properties.prime_remastered.objects.ActorMP1 import ActorMP1
from retro_data_structures.properties.prime_remastered.objects.ColorModulateMP1 import ColorModulateMP1
from retro_data_structures.properties.prime_remastered.objects.CounterMP1 import CounterMP1
from retro_data_structures.properties.prime_remastered.objects.DebugActorMP1 import DebugActorMP1
from retro_data_structures.properties.prime_remastered.objects.WaypointMP1 import WaypointMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerMP1 import PlayerMP1
from retro_data_structures.properties.prime_remastered.objects.SpawnPointMP1 import SpawnPointMP1
from retro_data_structures.properties.prime_remastered.objects.EnergyProjectileMP1 import EnergyProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.ControllerActionMP1 import ControllerActionMP1
from retro_data_structures.properties.prime_remastered.objects.PlasmaProjectileMP1 import PlasmaProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.BombMP1 import BombMP1
from retro_data_structures.properties.prime_remastered.objects.PowerBombMP1 import PowerBombMP1
from retro_data_structures.properties.prime_remastered.objects.NewFlameThrowerMP1 import NewFlameThrowerMP1
from retro_data_structures.properties.prime_remastered.objects.WaveBusterMP1 import WaveBusterMP1
from retro_data_structures.properties.prime_remastered.objects.ExplosionMP1 import ExplosionMP1
from retro_data_structures.properties.prime_remastered.objects.ShockWaveMP1 import ShockWaveMP1
from retro_data_structures.properties.prime_remastered.objects.FlameThrowerMP1 import FlameThrowerMP1
from retro_data_structures.properties.prime_remastered.objects.IceAttackProjectileMP1 import IceAttackProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.DamageEffectMP1 import DamageEffectMP1
from retro_data_structures.properties.prime_remastered.objects.CollisionActorMP1 import CollisionActorMP1
from retro_data_structures.properties.prime_remastered.objects.ScriptRelayMP1 import ScriptRelayMP1
from retro_data_structures.properties.prime_remastered.objects.TimerMP1 import TimerMP1
from retro_data_structures.properties.prime_remastered.objects.TriggerMP1 import TriggerMP1
from retro_data_structures.properties.prime_remastered.objects.SwitchMP1 import SwitchMP1
from retro_data_structures.properties.prime_remastered.objects.AiJumpPointMP1 import AiJumpPointMP1
from retro_data_structures.properties.prime_remastered.objects.RumbleEffectMP1 import RumbleEffectMP1
from retro_data_structures.properties.prime_remastered.objects.ActorKeyframeMP1 import ActorKeyframeMP1
from retro_data_structures.properties.prime_remastered.objects.SteamMP1 import SteamMP1
from retro_data_structures.properties.prime_remastered.objects.BallTriggerMP1 import BallTriggerMP1
from retro_data_structures.properties.prime_remastered.objects.FirstPersonCameraMP1 import FirstPersonCameraMP1
from retro_data_structures.properties.prime_remastered.objects.BallCameraMP1 import BallCameraMP1
from retro_data_structures.properties.prime_remastered.objects.FreeCameraMP1 import FreeCameraMP1
from retro_data_structures.properties.prime_remastered.objects.InterpolationCameraMP1 import InterpolationCameraMP1
from retro_data_structures.properties.prime_remastered.objects.SpecialFunctionMP1 import SpecialFunctionMP1
from retro_data_structures.properties.prime_remastered.objects.AmbientAIMP1 import AmbientAIMP1
from retro_data_structures.properties.prime_remastered.objects.ActorRotateMP1 import ActorRotateMP1
from retro_data_structures.properties.prime_remastered.objects.MemoryRelayMP1 import MemoryRelayMP1
from retro_data_structures.properties.prime_remastered.objects.PlatformMP1 import PlatformMP1
from retro_data_structures.properties.prime_remastered.objects.EffectMP1 import EffectMP1
from retro_data_structures.properties.prime_remastered.objects.HUDMemoMP1 import HUDMemoMP1
from retro_data_structures.properties.prime_remastered.objects.DamageableTriggerMP1 import DamageableTriggerMP1
from retro_data_structures.properties.prime_remastered.objects.WaterMP1 import WaterMP1
from retro_data_structures.properties.prime_remastered.objects.MagdoliteMP1 import MagdoliteMP1
from retro_data_structures.properties.prime_remastered.objects.JellyZapMP1 import JellyZapMP1
from retro_data_structures.properties.prime_remastered.objects.WarWaspMP1 import WarWaspMP1
from retro_data_structures.properties.prime_remastered.objects.IceSheegothMP1 import IceSheegothMP1
from retro_data_structures.properties.prime_remastered.objects.GarBeetleMP1 import GarBeetleMP1
from retro_data_structures.properties.prime_remastered.objects.FlickerBatMP1 import FlickerBatMP1
from retro_data_structures.properties.prime_remastered.objects.ParasiteMP1 import ParasiteMP1
from retro_data_structures.properties.prime_remastered.objects.FlaahgraRendererMP1Runtime import (
    FlaahgraRendererMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.FlaahgraPlantsMP1Runtime import FlaahgraPlantsMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.FlaahgraProjectileMP1Runtime import (
    FlaahgraProjectileMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.FlaahgraTentacleMP1 import FlaahgraTentacleMP1
from retro_data_structures.properties.prime_remastered.objects.FlaahgraMP1 import FlaahgraMP1
from retro_data_structures.properties.prime_remastered.objects.FireFleaMP1 import FireFleaMP1
from retro_data_structures.properties.prime_remastered.objects.EyeBallMP1 import EyeBallMP1
from retro_data_structures.properties.prime_remastered.objects.PuddleSporeMP1 import PuddleSporeMP1
from retro_data_structures.properties.prime_remastered.objects.OmegaPirateMP1 import OmegaPirateMP1
from retro_data_structures.properties.prime_remastered.objects.ElitePirateMP1 import ElitePirateMP1
from retro_data_structures.properties.prime_remastered.objects.SpacePirateMP1 import SpacePirateMP1
from retro_data_structures.properties.prime_remastered.objects.DroneMP1 import DroneMP1
from retro_data_structures.properties.prime_remastered.objects.ChozoGhostMP1 import ChozoGhostMP1
from retro_data_structures.properties.prime_remastered.objects.BurrowerMP1 import BurrowerMP1
from retro_data_structures.properties.prime_remastered.objects.FlyingPirateMP1 import FlyingPirateMP1
from retro_data_structures.properties.prime_remastered.objects.BloodFlowerMP1 import BloodFlowerMP1
from retro_data_structures.properties.prime_remastered.objects.TryclopsMP1 import TryclopsMP1
from retro_data_structures.properties.prime_remastered.objects.BabygothMP1 import BabygothMP1
from retro_data_structures.properties.prime_remastered.objects.RidleyMP1 import RidleyMP1
from retro_data_structures.properties.prime_remastered.objects.BouncyGrenadeMP1 import BouncyGrenadeMP1
from retro_data_structures.properties.prime_remastered.objects.PufferMP1 import PufferMP1
from retro_data_structures.properties.prime_remastered.objects.OculusMP1 import OculusMP1
from retro_data_structures.properties.prime_remastered.objects.GeemerMP1 import GeemerMP1
from retro_data_structures.properties.prime_remastered.objects.AtomicBetaMP1 import AtomicBetaMP1
from retro_data_structures.properties.prime_remastered.objects.AtomicAlphaMP1 import AtomicAlphaMP1
from retro_data_structures.properties.prime_remastered.objects.AThardusRockProjectileMP1 import (
    AThardusRockProjectileMP1,
)
from retro_data_structures.properties.prime_remastered.objects.ThardusMP1 import ThardusMP1
from retro_data_structures.properties.prime_remastered.objects.WorldLightFaderMP1 import WorldLightFaderMP1
from retro_data_structures.properties.prime_remastered.objects.ShadowProjectorMP1 import ShadowProjectorMP1
from retro_data_structures.properties.prime_remastered.objects.SpankWeedMP1 import SpankWeedMP1
from retro_data_structures.properties.prime_remastered.objects.SpindleCameraMP1 import SpindleCameraMP1
from retro_data_structures.properties.prime_remastered.objects.ThermalHeatFaderMP1 import ThermalHeatFaderMP1
from retro_data_structures.properties.prime_remastered.objects.TeamAiMgrMP1 import TeamAiMgrMP1
from retro_data_structures.properties.prime_remastered.objects.RippleMP1 import RippleMP1
from retro_data_structures.properties.prime_remastered.objects.IntroBossMP1 import IntroBossMP1
from retro_data_structures.properties.prime_remastered.objects.TargetingPointMP1 import TargetingPointMP1
from retro_data_structures.properties.prime_remastered.objects.SpiderBallWaypointMP1 import SpiderBallWaypointMP1
from retro_data_structures.properties.prime_remastered.objects.SpiderBallAttractionSurfaceMP1 import (
    SpiderBallAttractionSurfaceMP1,
)
from retro_data_structures.properties.prime_remastered.objects.PhazonPoolMP1 import PhazonPoolMP1
from retro_data_structures.properties.prime_remastered.objects.RadialDamageMP1 import RadialDamageMP1
from retro_data_structures.properties.prime_remastered.objects.CameraMP1 import CameraMP1
from retro_data_structures.properties.prime_remastered.objects.CoverPointMP1 import CoverPointMP1
from retro_data_structures.properties.prime_remastered.objects.PathCameraMP1 import PathCameraMP1
from retro_data_structures.properties.prime_remastered.objects.MazeNodeMP1 import MazeNodeMP1
from retro_data_structures.properties.prime_remastered.objects.PickupGeneratorMP1 import PickupGeneratorMP1
from retro_data_structures.properties.prime_remastered.objects.CameraPitchVolumeMP1 import CameraPitchVolumeMP1
from retro_data_structures.properties.prime_remastered.objects.ElectroMagneticPulseMP1 import ElectroMagneticPulseMP1
from retro_data_structures.properties.prime_remastered.objects.EnvFxDensityControllerMP1 import (
    EnvFxDensityControllerMP1,
)
from retro_data_structures.properties.prime_remastered.objects.VisorFlareMP1 import VisorFlareMP1
from retro_data_structures.properties.prime_remastered.objects.CameraHintMP1 import CameraHintMP1
from retro_data_structures.properties.prime_remastered.objects.DistanceFogMP1 import DistanceFogMP1
from retro_data_structures.properties.prime_remastered.objects.WallCrawlerSwarmMP1 import WallCrawlerSwarmMP1
from retro_data_structures.properties.prime_remastered.objects.GeneratorMP1 import GeneratorMP1
from retro_data_structures.properties.prime_remastered.objects.CameraHintTriggerMP1 import CameraHintTriggerMP1
from retro_data_structures.properties.prime_remastered.objects.GunTurretMP1 import GunTurretMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerHintMP1 import PlayerHintMP1
from retro_data_structures.properties.prime_remastered.objects.DebrisExtendedMP1 import DebrisExtendedMP1
from retro_data_structures.properties.prime_remastered.objects.RoomAcousticsMP1 import RoomAcousticsMP1
from retro_data_structures.properties.prime_remastered.objects.DoorMP1 import DoorMP1
from retro_data_structures.properties.prime_remastered.objects.ContraptionMP1 import ContraptionMP1
from retro_data_structures.properties.prime_remastered.objects.GrapplePointMP1 import GrapplePointMP1
from retro_data_structures.properties.prime_remastered.objects.PickupMP1 import PickupMP1
from retro_data_structures.properties.prime_remastered.objects.NotSTD_DockMP1 import NotSTD_DockMP1
from retro_data_structures.properties.prime_remastered.objects.RandomRelayMP1 import RandomRelayMP1
from retro_data_structures.properties.prime_remastered.objects.DebrisMP1 import DebrisMP1
from retro_data_structures.properties.prime_remastered.objects.CameraShakerNewMP1 import CameraShakerNewMP1
from retro_data_structures.properties.prime_remastered.objects.CameraShakerOldMP1 import CameraShakerOldMP1
from retro_data_structures.properties.prime_remastered.objects.VisorGooMP1 import VisorGooMP1
from retro_data_structures.properties.prime_remastered.objects.MidiMP1 import MidiMP1
from retro_data_structures.properties.prime_remastered.objects.SoundMP1 import SoundMP1
from retro_data_structures.properties.prime_remastered.objects.StreamedAudioMP1 import StreamedAudioMP1
from retro_data_structures.properties.prime_remastered.objects.CameraFilterKeyframeMP1 import CameraFilterKeyframeMP1
from retro_data_structures.properties.prime_remastered.objects.WorldTeleporterTooMP1 import WorldTeleporterTooMP1
from retro_data_structures.properties.prime_remastered.objects.CameraBlurKeyframeMP1 import CameraBlurKeyframeMP1
from retro_data_structures.properties.prime_remastered.objects.PointOfInterestMP1 import PointOfInterestMP1
from retro_data_structures.properties.prime_remastered.objects.AreaAttributesMP1 import AreaAttributesMP1
from retro_data_structures.properties.prime_remastered.objects.CameraWaypointMP1 import CameraWaypointMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerActorMP1 import PlayerActorMP1
from retro_data_structures.properties.prime_remastered.objects.MetareeMP1 import MetareeMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidBetaMP1 import MetroidBetaMP1
from retro_data_structures.properties.prime_remastered.objects.SeedlingMP1 import SeedlingMP1
from retro_data_structures.properties.prime_remastered.objects.TargetableProjectileMP1 import TargetableProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.RipperMP1 import RipperMP1
from retro_data_structures.properties.prime_remastered.objects.SnakeWeedSwarmMP1 import SnakeWeedSwarmMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidMP1 import MetroidMP1
from retro_data_structures.properties.prime_remastered.objects.PuddleToadGammaMP1 import PuddleToadGammaMP1
from retro_data_structures.properties.prime_remastered.objects.FishCloudModifierMP1 import FishCloudModifierMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidPrimeRelayMP1 import MetroidPrimeRelayMP1
from retro_data_structures.properties.prime_remastered.objects.GrapplePointMP1Runtime import GrapplePointMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.ControlledPlatformMP1Runtime import (
    ControlledPlatformMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.FishCloudMP1 import FishCloudMP1
from retro_data_structures.properties.prime_remastered.objects.PhazonHealingNoduleMP1 import PhazonHealingNoduleMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidPrimeMP1 import MetroidPrimeMP1
from retro_data_structures.properties.prime_remastered.objects.ProxyPlayerMP1 import ProxyPlayerMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidPrimeStage2MP1 import MetroidPrimeStage2MP1
from retro_data_structures.properties.prime_remastered.objects.VisorFlareMP1Runtime import VisorFlareMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.DroneLaserMP1Runtime import DroneLaserMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.DeathCameraEffectMP1Runtime import (
    DeathCameraEffectMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.ElitePirateGrenadeLauncherMP1Runtime import (
    ElitePirateGrenadeLauncherMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.PoisonProjectileMP1 import PoisonProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.MissileTargetMP1 import MissileTargetMP1
from retro_data_structures.properties.prime_remastered.objects.DestroyableRockMP1Runtime import (
    DestroyableRockMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.RoomOcclusionOverrideMP1 import RoomOcclusionOverrideMP1
from retro_data_structures.properties.prime_remastered.objects.ElectricBeamProjectileMP1Runtime import (
    ElectricBeamProjectileMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.CameraOverrideMP1 import CameraOverrideMP1
from retro_data_structures.properties.prime_remastered.objects.AnimatedCameraMP1 import AnimatedCameraMP1
from retro_data_structures.properties.prime_remastered.objects.ARepulsorMP1 import ARepulsorMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerStateChangeMP1 import PlayerStateChangeMP1
from retro_data_structures.properties.prime_remastered.objects.AEnergyBallMP1 import AEnergyBallMP1
from retro_data_structures.properties.prime_remastered.objects.AScriptBeamMP1 import AScriptBeamMP1
from retro_data_structures.properties.prime_remastered.objects.SustainedPlayerDamageMP1Runtime import (
    SustainedPlayerDamageMP1Runtime,
)
from retro_data_structures.properties.prime_remastered.objects.HUDManagerMP1 import HUDManagerMP1
from retro_data_structures.properties.prime_remastered.objects.ScriptHUDBillboardEffectMP1 import (
    ScriptHUDBillboardEffectMP1,
)
from retro_data_structures.properties.prime_remastered.objects.RumbleEventResponderMP1 import RumbleEventResponderMP1
from retro_data_structures.properties.prime_remastered.objects.CinematicStateProxyMP1 import CinematicStateProxyMP1
from retro_data_structures.properties.prime_remastered.objects.HUDBillboardFreezeEffectTestMP1 import (
    HUDBillboardFreezeEffectTestMP1,
)
from retro_data_structures.properties.prime_remastered.objects.ScriptedOcclusionVolumeMP1 import (
    ScriptedOcclusionVolumeMP1,
)
from retro_data_structures.properties.prime_remastered.objects.MaterialVariableDriverMP1 import (
    MaterialVariableDriverMP1,
)
from retro_data_structures.properties.prime_remastered.objects.EffectProxyMP1 import EffectProxyMP1
from retro_data_structures.properties.prime_remastered.objects.CinematicMP1 import CinematicMP1
from retro_data_structures.properties.prime_remastered.objects.PhazonDriverMP1 import PhazonDriverMP1
from retro_data_structures.properties.prime_remastered.objects.AmbientParticleEffectPrimitiveShapeProviderMP1 import (
    AmbientParticleEffectPrimitiveShapeProviderMP1,
)
from retro_data_structures.properties.prime_remastered.objects.XRayHintMP1 import XRayHintMP1
from retro_data_structures.properties.prime_remastered.objects.CameraWaterStateProxyMP1 import CameraWaterStateProxyMP1
from retro_data_structures.properties.prime_remastered.objects.WaterTransitionMP1 import WaterTransitionMP1
from retro_data_structures.properties.prime_remastered.objects.AreaOcclusionModifierMP1 import AreaOcclusionModifierMP1
from retro_data_structures.properties.prime_remastered.objects.BakedLightingPriorityModifierMP1 import (
    BakedLightingPriorityModifierMP1,
)
from retro_data_structures.properties.prime_remastered.objects.AutoExposureHintMP1 import AutoExposureHintMP1
from retro_data_structures.properties.prime_remastered.objects.ActorIceDarkenerMP1 import ActorIceDarkenerMP1
from retro_data_structures.properties.prime_remastered.objects.AABoxMagnet import AABoxMagnet
from retro_data_structures.properties.prime_remastered.objects.AIGenerator import AIGenerator
from retro_data_structures.properties.prime_remastered.objects.AIGeneratorSelector import AIGeneratorSelector
from retro_data_structures.properties.prime_remastered.objects.AIPostOwner import AIPostOwner
from retro_data_structures.properties.prime_remastered.objects.AITeleportProxy import AITeleportProxy
from retro_data_structures.properties.prime_remastered.objects.ActionControlPoint import ActionControlPoint
from retro_data_structures.properties.prime_remastered.objects.ActorCollision import ActorCollision
from retro_data_structures.properties.prime_remastered.objects.ActorInteraction import ActorInteraction
from retro_data_structures.properties.prime_remastered.objects.ActorKeyframe import ActorKeyframe
from retro_data_structures.properties.prime_remastered.objects.ActorKeyframePhaseResponder import (
    ActorKeyframePhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.ActorVertexAnimationPhaseResponder import (
    ActorVertexAnimationPhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.ActorVertexAnimationPlayList import (
    ActorVertexAnimationPlayList,
)
from retro_data_structures.properties.prime_remastered.objects.AdapterManager import AdapterManager
from retro_data_structures.properties.prime_remastered.objects.AddActorEntityFlag import AddActorEntityFlag
from retro_data_structures.properties.prime_remastered.objects.AiTarget import AiTarget
from retro_data_structures.properties.prime_remastered.objects.AiTargetManager import AiTargetManager
from retro_data_structures.properties.prime_remastered.objects.AmbientParticleEffect import AmbientParticleEffect
from retro_data_structures.properties.prime_remastered.objects.AnalogDriver import AnalogDriver
from retro_data_structures.properties.prime_remastered.objects.AnchorPoint import AnchorPoint
from retro_data_structures.properties.prime_remastered.objects.AngleCompare import AngleCompare
from retro_data_structures.properties.prime_remastered.objects.AnimVisibilityStateGroupManager import (
    AnimVisibilityStateGroupManager,
)
from retro_data_structures.properties.prime_remastered.objects.AnimatedMeter import AnimatedMeter
from retro_data_structures.properties.prime_remastered.objects.AnimatedMeterPhaseResponder import (
    AnimatedMeterPhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.AnimatedSprite import AnimatedSprite
from retro_data_structures.properties.prime_remastered.objects.AnimationController import AnimationController
from retro_data_structures.properties.prime_remastered.objects.AnimationEventListener import AnimationEventListener
from retro_data_structures.properties.prime_remastered.objects.AnimationGridController import AnimationGridController
from retro_data_structures.properties.prime_remastered.objects.AnimationMountRider import AnimationMountRider
from retro_data_structures.properties.prime_remastered.objects.AnimationPlaybackRate import AnimationPlaybackRate
from retro_data_structures.properties.prime_remastered.objects.AnimationRateModifier import AnimationRateModifier
from retro_data_structures.properties.prime_remastered.objects.AnimationUserEventRouter import AnimationUserEventRouter
from retro_data_structures.properties.prime_remastered.objects.AnimationVariableReal import AnimationVariableReal
from retro_data_structures.properties.prime_remastered.objects.ApplyDamage import ApplyDamage
from retro_data_structures.properties.prime_remastered.objects.AttackManager import AttackManager
from retro_data_structures.properties.prime_remastered.objects.AttackManagerTest import AttackManagerTest
from retro_data_structures.properties.prime_remastered.objects.AudioBusController import AudioBusController
from retro_data_structures.properties.prime_remastered.objects.AudioBusDriver import AudioBusDriver
from retro_data_structures.properties.prime_remastered.objects.AudioBusDriverInteractor import AudioBusDriverInteractor
from retro_data_structures.properties.prime_remastered.objects.AudioBusMixer import AudioBusMixer
from retro_data_structures.properties.prime_remastered.objects.AudioBusPhaseResponder import AudioBusPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.AudioEmitter import AudioEmitter
from retro_data_structures.properties.prime_remastered.objects.AudioObstruction import AudioObstruction
from retro_data_structures.properties.prime_remastered.objects.AudioObstructionOcclusionOverride import (
    AudioObstructionOcclusionOverride,
)
from retro_data_structures.properties.prime_remastered.objects.AudioOcclusionVolume import AudioOcclusionVolume
from retro_data_structures.properties.prime_remastered.objects.AudioOutputEffects import AudioOutputEffects
from retro_data_structures.properties.prime_remastered.objects.AudioPluginEffect import AudioPluginEffect
from retro_data_structures.properties.prime_remastered.objects.AudioPluginEffectCrossfadePhaseResponder import (
    AudioPluginEffectCrossfadePhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.AudioPluginEffectCrossfadeSend import (
    AudioPluginEffectCrossfadeSend,
)
from retro_data_structures.properties.prime_remastered.objects.AudioSampleBank import AudioSampleBank
from retro_data_structures.properties.prime_remastered.objects.AudioSampler import AudioSampler
from retro_data_structures.properties.prime_remastered.objects.AudioSamplerPhaseResponder import (
    AudioSamplerPhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.AudioSamplerProxy import AudioSamplerProxy
from retro_data_structures.properties.prime_remastered.objects.AutoExposureHint import AutoExposureHint
from retro_data_structures.properties.prime_remastered.objects.BGMHint import BGMHint
from retro_data_structures.properties.prime_remastered.objects.Backlight import Backlight
from retro_data_structures.properties.prime_remastered.objects.Beam import Beam
from retro_data_structures.properties.prime_remastered.objects.BlackboardBoolean import BlackboardBoolean
from retro_data_structures.properties.prime_remastered.objects.BlackboardBooleanWriter import BlackboardBooleanWriter
from retro_data_structures.properties.prime_remastered.objects.BlackboardPhaseRelay import BlackboardPhaseRelay
from retro_data_structures.properties.prime_remastered.objects.BlackboardPhaseRelayWriter import (
    BlackboardPhaseRelayWriter,
)
from retro_data_structures.properties.prime_remastered.objects.BlackboardRealNumber import BlackboardRealNumber
from retro_data_structures.properties.prime_remastered.objects.BlackboardRealNumberWriter import (
    BlackboardRealNumberWriter,
)
from retro_data_structures.properties.prime_remastered.objects.BloomEffect import BloomEffect
from retro_data_structures.properties.prime_remastered.objects.BloomEffectHint import BloomEffectHint
from retro_data_structures.properties.prime_remastered.objects.BoolToRealMap import BoolToRealMap
from retro_data_structures.properties.prime_remastered.objects.Boolean import Boolean
from retro_data_structures.properties.prime_remastered.objects.BoostPad import BoostPad
from retro_data_structures.properties.prime_remastered.objects.BossMeterState import BossMeterState
from retro_data_structures.properties.prime_remastered.objects.BroadcastAudioEvent import BroadcastAudioEvent
from retro_data_structures.properties.prime_remastered.objects.BroadcastAudioEventListener import (
    BroadcastAudioEventListener,
)
from retro_data_structures.properties.prime_remastered.objects.BroadcastGlobal import BroadcastGlobal
from retro_data_structures.properties.prime_remastered.objects.BroadcastGlobalListener import BroadcastGlobalListener
from retro_data_structures.properties.prime_remastered.objects.BroadcastSpatial import BroadcastSpatial
from retro_data_structures.properties.prime_remastered.objects.BroadcastSpatialListener import BroadcastSpatialListener
from retro_data_structures.properties.prime_remastered.objects.CameraAdditiveFOV import CameraAdditiveFOV
from retro_data_structures.properties.prime_remastered.objects.CameraFilter import CameraFilter
from retro_data_structures.properties.prime_remastered.objects.CameraHint import CameraHint
from retro_data_structures.properties.prime_remastered.objects.CameraLetterBox import CameraLetterBox
from retro_data_structures.properties.prime_remastered.objects.CameraManager import CameraManager
from retro_data_structures.properties.prime_remastered.objects.CameraPointOfInterest import CameraPointOfInterest
from retro_data_structures.properties.prime_remastered.objects.CameraPredictivePitchHint import (
    CameraPredictivePitchHint,
)
from retro_data_structures.properties.prime_remastered.objects.CameraPredictiveYawHint import CameraPredictiveYawHint
from retro_data_structures.properties.prime_remastered.objects.CameraProxy import CameraProxy
from retro_data_structures.properties.prime_remastered.objects.CameraShaker import CameraShaker
from retro_data_structures.properties.prime_remastered.objects.CameraSystemHint import CameraSystemHint
from retro_data_structures.properties.prime_remastered.objects.CameraTarget import CameraTarget
from retro_data_structures.properties.prime_remastered.objects.CameraTargetCreature import CameraTargetCreature
from retro_data_structures.properties.prime_remastered.objects.CameraTargetPlayer import CameraTargetPlayer
from retro_data_structures.properties.prime_remastered.objects.CameraTargetProxy import CameraTargetProxy
from retro_data_structures.properties.prime_remastered.objects.CausticVolume import CausticVolume
from retro_data_structures.properties.prime_remastered.objects.ChainLightning import ChainLightning
from retro_data_structures.properties.prime_remastered.objects.CharacterPrimitives import CharacterPrimitives
from retro_data_structures.properties.prime_remastered.objects.CharacterPrimitivesCollision import (
    CharacterPrimitivesCollision,
)
from retro_data_structures.properties.prime_remastered.objects.Checkpoint import Checkpoint
from retro_data_structures.properties.prime_remastered.objects.Choreographer import Choreographer
from retro_data_structures.properties.prime_remastered.objects.ChromaticAberration import ChromaticAberration
from retro_data_structures.properties.prime_remastered.objects.Cinematic import Cinematic
from retro_data_structures.properties.prime_remastered.objects.CinematicActor import CinematicActor
from retro_data_structures.properties.prime_remastered.objects.CinematicCameraShot import CinematicCameraShot
from retro_data_structures.properties.prime_remastered.objects.CinematicSkipHandler import CinematicSkipHandler
from retro_data_structures.properties.prime_remastered.objects.CollisionAvoidanceManager import (
    CollisionAvoidanceManager,
)
from retro_data_structures.properties.prime_remastered.objects.CollisionLogic import CollisionLogic
from retro_data_structures.properties.prime_remastered.objects.CollisionProbe import CollisionProbe
from retro_data_structures.properties.prime_remastered.objects.CollisionWithWorld import CollisionWithWorld
from retro_data_structures.properties.prime_remastered.objects.ColorGrade import ColorGrade
from retro_data_structures.properties.prime_remastered.objects.ColorGradeHint import ColorGradeHint
from retro_data_structures.properties.prime_remastered.objects.ColorModifier import ColorModifier
from retro_data_structures.properties.prime_remastered.objects.ColorSampler import ColorSampler
from retro_data_structures.properties.prime_remastered.objects.CombatStateProxy import CombatStateProxy
from retro_data_structures.properties.prime_remastered.objects.Condition import Condition
from retro_data_structures.properties.prime_remastered.objects.ContextInteraction import ContextInteraction
from retro_data_structures.properties.prime_remastered.objects.ControlCommandDisabler import ControlCommandDisabler
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingAdd import ControlCommandMappingAdd
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingAnd import ControlCommandMappingAnd
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuBoolean import (
    ControlCommandMappingDebugMenuBoolean,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuInt import (
    ControlCommandMappingDebugMenuInt,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuRealEvaluator import (
    ControlCommandMappingDebugMenuRealEvaluator,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuRealMultiplier import (
    ControlCommandMappingDebugMenuRealMultiplier,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingMultiply import (
    ControlCommandMappingMultiply,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNegate import (
    ControlCommandMappingNegate,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNegativeOne import (
    ControlCommandMappingNegativeOne,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNode import (
    ControlCommandMappingNode,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNot import ControlCommandMappingNot
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingOne import ControlCommandMappingOne
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingOr import ControlCommandMappingOr
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingPhysical import (
    ControlCommandMappingPhysical,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingScriptedReal import (
    ControlCommandMappingScriptedReal,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingSpline import (
    ControlCommandMappingSpline,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingZero import (
    ControlCommandMappingZero,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingsDefinition import (
    ControlCommandMappingsDefinition,
)
from retro_data_structures.properties.prime_remastered.objects.ControlCommandSpoofer import ControlCommandSpoofer
from retro_data_structures.properties.prime_remastered.objects.ControlSchemeAccessor import ControlSchemeAccessor
from retro_data_structures.properties.prime_remastered.objects.ControlSchemesDefinition import ControlSchemesDefinition
from retro_data_structures.properties.prime_remastered.objects.ControlSplineMappingsDefinition import (
    ControlSplineMappingsDefinition,
)
from retro_data_structures.properties.prime_remastered.objects.ControllerAction import ControllerAction
from retro_data_structures.properties.prime_remastered.objects.ControllerAnalogInputDriver import (
    ControllerAnalogInputDriver,
)
from retro_data_structures.properties.prime_remastered.objects.ControllerAnalogMovement import ControllerAnalogMovement
from retro_data_structures.properties.prime_remastered.objects.ControllerAnalogShapeAction import (
    ControllerAnalogShapeAction,
)
from retro_data_structures.properties.prime_remastered.objects.ControllerMotionDriver import ControllerMotionDriver
from retro_data_structures.properties.prime_remastered.objects.ConveyorModifier import ConveyorModifier
from retro_data_structures.properties.prime_remastered.objects.Counter import Counter
from retro_data_structures.properties.prime_remastered.objects.CounterAdapter import CounterAdapter
from retro_data_structures.properties.prime_remastered.objects.CounterPhaseResponder import CounterPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.CoverPoint import CoverPoint
from retro_data_structures.properties.prime_remastered.objects.CreatureActionBroadcaster import (
    CreatureActionBroadcaster,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureActionPatternBehavior import (
    CreatureActionPatternBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureAiming import CreatureAiming
from retro_data_structures.properties.prime_remastered.objects.CreatureAmbushBehavior import CreatureAmbushBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureArmor import CreatureArmor
from retro_data_structures.properties.prime_remastered.objects.CreatureAttackPathBehavior import (
    CreatureAttackPathBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureBase import CreatureBase
from retro_data_structures.properties.prime_remastered.objects.CreatureChangePostureBehavior import (
    CreatureChangePostureBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureCollisionAvoidance import (
    CreatureCollisionAvoidance,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureContextInteraction import (
    CreatureContextInteraction,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureContextInteractionBehavior import (
    CreatureContextInteractionBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureCoverCombatBehavior import (
    CreatureCoverCombatBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureDeployActionBehavior import (
    CreatureDeployActionBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureDespawnBehavior import CreatureDespawnBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureEvadeBehavior import CreatureEvadeBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureFallBehavior import CreatureFallBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureFireDamage import CreatureFireDamage
from retro_data_structures.properties.prime_remastered.objects.CreatureFleeBehavior import CreatureFleeBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureFlinch import CreatureFlinch
from retro_data_structures.properties.prime_remastered.objects.CreatureGrabTarget import CreatureGrabTarget
from retro_data_structures.properties.prime_remastered.objects.CreatureHeadTracking import CreatureHeadTracking
from retro_data_structures.properties.prime_remastered.objects.CreatureHealth import CreatureHealth
from retro_data_structures.properties.prime_remastered.objects.CreatureHecklerBehavior import CreatureHecklerBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureHitReactionBehavior import (
    CreatureHitReactionBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureHurlBehavior import CreatureHurlBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureIceDamage import CreatureIceDamage
from retro_data_structures.properties.prime_remastered.objects.CreatureLeashBehavior import CreatureLeashBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureMeleeCombatBehavior import (
    CreatureMeleeCombatBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureMovement import CreatureMovement
from retro_data_structures.properties.prime_remastered.objects.CreatureNavigateBehavior import CreatureNavigateBehavior
from retro_data_structures.properties.prime_remastered.objects.CreaturePatrolBehavior import CreaturePatrolBehavior
from retro_data_structures.properties.prime_remastered.objects.CreaturePositionLogic_WaypointScripting import (
    CreaturePositionLogic_WaypointScripting,
)
from retro_data_structures.properties.prime_remastered.objects.CreaturePositioning import CreaturePositioning
from retro_data_structures.properties.prime_remastered.objects.CreaturePositioningManager import (
    CreaturePositioningManager,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureProjectileLauncher import (
    CreatureProjectileLauncher,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureProneBehavior import CreatureProneBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureRangedCombatBehavior import (
    CreatureRangedCombatBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureRules import CreatureRules
from retro_data_structures.properties.prime_remastered.objects.CreatureScriptedActionBehavior import (
    CreatureScriptedActionBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureScriptedAnimationBehavior import (
    CreatureScriptedAnimationBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureScriptedJumpBehavior import (
    CreatureScriptedJumpBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureSecondaryActions import CreatureSecondaryActions
from retro_data_structures.properties.prime_remastered.objects.CreatureSecondaryAnimation import (
    CreatureSecondaryAnimation,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureSniperBehavior import CreatureSniperBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureSpawnBehavior import CreatureSpawnBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureSplineFollowBehavior import (
    CreatureSplineFollowBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureTargetable import CreatureTargetable
from retro_data_structures.properties.prime_remastered.objects.CreatureTargeting import CreatureTargeting
from retro_data_structures.properties.prime_remastered.objects.CreatureThunderDamage import CreatureThunderDamage
from retro_data_structures.properties.prime_remastered.objects.CreatureTurnBehavior import CreatureTurnBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureTurnProcedural import CreatureTurnProcedural
from retro_data_structures.properties.prime_remastered.objects.CreatureWaitAtPositionBehavior import (
    CreatureWaitAtPositionBehavior,
)
from retro_data_structures.properties.prime_remastered.objects.CreatureWanderBehavior import CreatureWanderBehavior
from retro_data_structures.properties.prime_remastered.objects.Credits import Credits
from retro_data_structures.properties.prime_remastered.objects.CustomInterpolation import CustomInterpolation
from retro_data_structures.properties.prime_remastered.objects.DSP import DSP
from retro_data_structures.properties.prime_remastered.objects.DamageRelay import DamageRelay
from retro_data_structures.properties.prime_remastered.objects.DamageResponderVulnerability import (
    DamageResponderVulnerability,
)
from retro_data_structures.properties.prime_remastered.objects.DebugMenuItemsDefinition import DebugMenuItemsDefinition
from retro_data_structures.properties.prime_remastered.objects.DetectionPlane import DetectionPlane
from retro_data_structures.properties.prime_remastered.objects.DistanceCompare import DistanceCompare
from retro_data_structures.properties.prime_remastered.objects.DistanceCompareGroup import DistanceCompareGroup
from retro_data_structures.properties.prime_remastered.objects.Dock import Dock
from retro_data_structures.properties.prime_remastered.objects.DockDoor import DockDoor
from retro_data_structures.properties.prime_remastered.objects.Drivable import Drivable
from retro_data_structures.properties.prime_remastered.objects.DynamicActorCollision import DynamicActorCollision
from retro_data_structures.properties.prime_remastered.objects.DynamicActorControl import DynamicActorControl
from retro_data_structures.properties.prime_remastered.objects.DynamicControlScriptedRealDefinition import (
    DynamicControlScriptedRealDefinition,
)
from retro_data_structures.properties.prime_remastered.objects.DynamicLoadManager import DynamicLoadManager
from retro_data_structures.properties.prime_remastered.objects.Effect import Effect
from retro_data_structures.properties.prime_remastered.objects.EffectVariableDriver import EffectVariableDriver
from retro_data_structures.properties.prime_remastered.objects.EndGame import EndGame
from retro_data_structures.properties.prime_remastered.objects.EntityProperties import EntityProperties
from retro_data_structures.properties.prime_remastered.objects.EnumToRealMap import EnumToRealMap
from retro_data_structures.properties.prime_remastered.objects.Enumeration import Enumeration
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarListener import EnvironmentVarListener
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarModifier import EnvironmentVarModifier
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarQuery import EnvironmentVarQuery
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarSender import EnvironmentVarSender
from retro_data_structures.properties.prime_remastered.objects.Explosion import Explosion
from retro_data_structures.properties.prime_remastered.objects.FSMController import FSMController
from retro_data_structures.properties.prime_remastered.objects.FSMHotSwapper import FSMHotSwapper
from retro_data_structures.properties.prime_remastered.objects.FSMManager import FSMManager
from retro_data_structures.properties.prime_remastered.objects.FSMMessage import FSMMessage
from retro_data_structures.properties.prime_remastered.objects.Faction import Faction
from retro_data_structures.properties.prime_remastered.objects.FactionManager import FactionManager
from retro_data_structures.properties.prime_remastered.objects.FakePlayerControls import FakePlayerControls
from retro_data_structures.properties.prime_remastered.objects.FleePoint import FleePoint
from retro_data_structures.properties.prime_remastered.objects.FlowPath import FlowPath
from retro_data_structures.properties.prime_remastered.objects.FogShape import FogShape
from retro_data_structures.properties.prime_remastered.objects.FogVolume import FogVolume
from retro_data_structures.properties.prime_remastered.objects.Footprint import Footprint
from retro_data_structures.properties.prime_remastered.objects.FrontEndManager import FrontEndManager
from retro_data_structures.properties.prime_remastered.objects.GameFlowHub import GameFlowHub
from retro_data_structures.properties.prime_remastered.objects.GameFlowProxy import GameFlowProxy
from retro_data_structures.properties.prime_remastered.objects.GameFlowRelay import GameFlowRelay
from retro_data_structures.properties.prime_remastered.objects.GameOptionsAccessor import GameOptionsAccessor
from retro_data_structures.properties.prime_remastered.objects.GameOptionsDefinition import GameOptionsDefinition
from retro_data_structures.properties.prime_remastered.objects.GameVariableAccess import GameVariableAccess
from retro_data_structures.properties.prime_remastered.objects.Generator import Generator
from retro_data_structures.properties.prime_remastered.objects.GenericAimTarget import GenericAimTarget
from retro_data_structures.properties.prime_remastered.objects.GenericSplineControl import GenericSplineControl
from retro_data_structures.properties.prime_remastered.objects.GibManager import GibManager
from retro_data_structures.properties.prime_remastered.objects.GlobalStateMonitor import GlobalStateMonitor
from retro_data_structures.properties.prime_remastered.objects.GradientAmbient import GradientAmbient
from retro_data_structures.properties.prime_remastered.objects.GraphicalTransition import GraphicalTransition
from retro_data_structures.properties.prime_remastered.objects.GroupSpawn import GroupSpawn
from retro_data_structures.properties.prime_remastered.objects.HUDSuppressor import HUDSuppressor
from retro_data_structures.properties.prime_remastered.objects.HardwareProxy import HardwareProxy
from retro_data_structures.properties.prime_remastered.objects.Health import Health
from retro_data_structures.properties.prime_remastered.objects.HealthDisplay import HealthDisplay
from retro_data_structures.properties.prime_remastered.objects.HealthDisplaySource import HealthDisplaySource
from retro_data_structures.properties.prime_remastered.objects.HealthPhases import HealthPhases
from retro_data_structures.properties.prime_remastered.objects.HeatDistortionHint import HeatDistortionHint
from retro_data_structures.properties.prime_remastered.objects.HeightfieldSurfaceDescription import (
    HeightfieldSurfaceDescription,
)
from retro_data_structures.properties.prime_remastered.objects.ImpulseDriver import ImpulseDriver
from retro_data_structures.properties.prime_remastered.objects.IncandescenceModulator import IncandescenceModulator
from retro_data_structures.properties.prime_remastered.objects.InputMacroPlayer import InputMacroPlayer
from retro_data_structures.properties.prime_remastered.objects.InputMacroRecorder import InputMacroRecorder
from retro_data_structures.properties.prime_remastered.objects.IntToRealMap import IntToRealMap
from retro_data_structures.properties.prime_remastered.objects.InventoryInitializer import InventoryInitializer
from retro_data_structures.properties.prime_remastered.objects.InventoryItem import InventoryItem
from retro_data_structures.properties.prime_remastered.objects.InventoryTextPane import InventoryTextPane
from retro_data_structures.properties.prime_remastered.objects.Label import Label
from retro_data_structures.properties.prime_remastered.objects.LavaFlowSurface import LavaFlowSurface
from retro_data_structures.properties.prime_remastered.objects.LavaRenderVolume import LavaRenderVolume
from retro_data_structures.properties.prime_remastered.objects.LevelDarkener import LevelDarkener
from retro_data_structures.properties.prime_remastered.objects.LightDynamic import LightDynamic
from retro_data_structures.properties.prime_remastered.objects.LightGroupProxy import LightGroupProxy
from retro_data_structures.properties.prime_remastered.objects.LightHint import LightHint
from retro_data_structures.properties.prime_remastered.objects.LightShafts import LightShafts
from retro_data_structures.properties.prime_remastered.objects.LightStatic import LightStatic
from retro_data_structures.properties.prime_remastered.objects.LineOfSight import LineOfSight
from retro_data_structures.properties.prime_remastered.objects.LiquidInhabitant import LiquidInhabitant
from retro_data_structures.properties.prime_remastered.objects.LiquidVolume import LiquidVolume
from retro_data_structures.properties.prime_remastered.objects.LoadUnitController import LoadUnitController
from retro_data_structures.properties.prime_remastered.objects.LogicGate import LogicGate
from retro_data_structures.properties.prime_remastered.objects.MIDIControllerMessageEmitter import (
    MIDIControllerMessageEmitter,
)
from retro_data_structures.properties.prime_remastered.objects.MIDIMatcher import MIDIMatcher
from retro_data_structures.properties.prime_remastered.objects.MIDINoteAdaptor import MIDINoteAdaptor
from retro_data_structures.properties.prime_remastered.objects.MIDINoteEmitter import MIDINoteEmitter
from retro_data_structures.properties.prime_remastered.objects.MIDIReceiver import MIDIReceiver
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderArpeggiator import MIDIResponderArpeggiator
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderChordMaker import MIDIResponderChordMaker
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderPatternMatcher import (
    MIDIResponderPatternMatcher,
)
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderSampler import MIDIResponderSampler
from retro_data_structures.properties.prime_remastered.objects.MIDIRetronome import MIDIRetronome
from retro_data_structures.properties.prime_remastered.objects.MIDISequence import MIDISequence
from retro_data_structures.properties.prime_remastered.objects.MIDITransmitter import MIDITransmitter
from retro_data_structures.properties.prime_remastered.objects.ModCon import ModCon
from retro_data_structures.properties.prime_remastered.objects.MusicData import MusicData
from retro_data_structures.properties.prime_remastered.objects.MusicStateController import MusicStateController
from retro_data_structures.properties.prime_remastered.objects.MusicStateTransitionData import MusicStateTransitionData
from retro_data_structures.properties.prime_remastered.objects.MusicSystemTransport import MusicSystemTransport
from retro_data_structures.properties.prime_remastered.objects.NavigationAreaLink import NavigationAreaLink
from retro_data_structures.properties.prime_remastered.objects.NavigationMesh import NavigationMesh
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshDock import NavigationMeshDock
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshDynamicObstruction import (
    NavigationMeshDynamicObstruction,
)
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshHint import NavigationMeshHint
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshIncludeExcludeHint import (
    NavigationMeshIncludeExcludeHint,
)
from retro_data_structures.properties.prime_remastered.objects.NavigationOffMeshLink import NavigationOffMeshLink
from retro_data_structures.properties.prime_remastered.objects.NavigationPathPoint import NavigationPathPoint
from retro_data_structures.properties.prime_remastered.objects.NavigationPathPointOffMeshLink import (
    NavigationPathPointOffMeshLink,
)
from retro_data_structures.properties.prime_remastered.objects.NearVisible import NearVisible
from retro_data_structures.properties.prime_remastered.objects.ObjectFollow import ObjectFollow
from retro_data_structures.properties.prime_remastered.objects.ObjectSelector import ObjectSelector
from retro_data_structures.properties.prime_remastered.objects.ObjectTeleport import ObjectTeleport
from retro_data_structures.properties.prime_remastered.objects.Occlusion import Occlusion
from retro_data_structures.properties.prime_remastered.objects.OrbitTarget import OrbitTarget
from retro_data_structures.properties.prime_remastered.objects.OriginatorProxy import OriginatorProxy
from retro_data_structures.properties.prime_remastered.objects.POIRoomController import POIRoomController
from retro_data_structures.properties.prime_remastered.objects.ParticleVolume import ParticleVolume
from retro_data_structures.properties.prime_remastered.objects.PathControl import PathControl
from retro_data_structures.properties.prime_remastered.objects.PathFind import PathFind
from retro_data_structures.properties.prime_remastered.objects.PathGenerator import PathGenerator
from retro_data_structures.properties.prime_remastered.objects.PathMovement import PathMovement
from retro_data_structures.properties.prime_remastered.objects.PathMovementMagnetizationPoint import (
    PathMovementMagnetizationPoint,
)
from retro_data_structures.properties.prime_remastered.objects.PatternMatcher import PatternMatcher
from retro_data_structures.properties.prime_remastered.objects.PerformanceGroupController import (
    PerformanceGroupController,
)
from retro_data_structures.properties.prime_remastered.objects.PerformanceHint import PerformanceHint
from retro_data_structures.properties.prime_remastered.objects.PeriodicAdditiveAnimationDriver import (
    PeriodicAdditiveAnimationDriver,
)
from retro_data_structures.properties.prime_remastered.objects.PhaseCombinator import PhaseCombinator
from retro_data_structures.properties.prime_remastered.objects.PhaseLooper import PhaseLooper
from retro_data_structures.properties.prime_remastered.objects.PhaseRelay import PhaseRelay
from retro_data_structures.properties.prime_remastered.objects.PhaseToEvents import PhaseToEvents
from retro_data_structures.properties.prime_remastered.objects.PhysicsDriver import PhysicsDriver
from retro_data_structures.properties.prime_remastered.objects.Pickup import Pickup
from retro_data_structures.properties.prime_remastered.objects.PickupDropper import PickupDropper
from retro_data_structures.properties.prime_remastered.objects.PickupManager import PickupManager
from retro_data_structures.properties.prime_remastered.objects.PlayerActor import PlayerActor
from retro_data_structures.properties.prime_remastered.objects.PlayerDeathFall import PlayerDeathFall
from retro_data_structures.properties.prime_remastered.objects.PlayerEventListener import PlayerEventListener
from retro_data_structures.properties.prime_remastered.objects.PlayerInventoryEffects import PlayerInventoryEffects
from retro_data_structures.properties.prime_remastered.objects.PlayerKeyframe import PlayerKeyframe
from retro_data_structures.properties.prime_remastered.objects.PlayerRespawn import PlayerRespawn
from retro_data_structures.properties.prime_remastered.objects.PlayerRoomTeleporter import PlayerRoomTeleporter
from retro_data_structures.properties.prime_remastered.objects.PlayerSpawnPoint_InputMacroRelay import (
    PlayerSpawnPoint_InputMacroRelay,
)
from retro_data_structures.properties.prime_remastered.objects.PlayerSpawnTeleporter import PlayerSpawnTeleporter
from retro_data_structures.properties.prime_remastered.objects.PlayerTeleport import PlayerTeleport
from retro_data_structures.properties.prime_remastered.objects.Playlist import Playlist
from retro_data_structures.properties.prime_remastered.objects.PoiObject import PoiObject
from retro_data_structures.properties.prime_remastered.objects.PointOfInterest import PointOfInterest
from retro_data_structures.properties.prime_remastered.objects.ProjectedShadowBlob import ProjectedShadowBlob
from retro_data_structures.properties.prime_remastered.objects.ProjectedSimpleShadowReceiver import (
    ProjectedSimpleShadowReceiver,
)
from retro_data_structures.properties.prime_remastered.objects.Projectile import Projectile
from retro_data_structures.properties.prime_remastered.objects.ProjectileIntersectionHint import (
    ProjectileIntersectionHint,
)
from retro_data_structures.properties.prime_remastered.objects.ProxyRegisteredEntity import ProxyRegisteredEntity
from retro_data_structures.properties.prime_remastered.objects.Reactivator import Reactivator
from retro_data_structures.properties.prime_remastered.objects.RealNumber import RealNumber
from retro_data_structures.properties.prime_remastered.objects.RealNumberComparison import RealNumberComparison
from retro_data_structures.properties.prime_remastered.objects.RealNumberDriver import RealNumberDriver
from retro_data_structures.properties.prime_remastered.objects.RealNumberFunction import RealNumberFunction
from retro_data_structures.properties.prime_remastered.objects.RealNumberPhaseResponder import RealNumberPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.RealToRealMap import RealToRealMap
from retro_data_structures.properties.prime_remastered.objects.RealValueRelay import RealValueRelay
from retro_data_structures.properties.prime_remastered.objects.ReflectionProbe import ReflectionProbe
from retro_data_structures.properties.prime_remastered.objects.RegisterEntity import RegisterEntity
from retro_data_structures.properties.prime_remastered.objects.Relay import Relay
from retro_data_structures.properties.prime_remastered.objects.RelayAttackTypePayload import RelayAttackTypePayload
from retro_data_structures.properties.prime_remastered.objects.RelayAutoFire import RelayAutoFire
from retro_data_structures.properties.prime_remastered.objects.RelayChoreography import RelayChoreography
from retro_data_structures.properties.prime_remastered.objects.RelayConditional import RelayConditional
from retro_data_structures.properties.prime_remastered.objects.RelayFrameDelay import RelayFrameDelay
from retro_data_structures.properties.prime_remastered.objects.RelayMemory import RelayMemory
from retro_data_structures.properties.prime_remastered.objects.RelayOriginatorFilter import RelayOriginatorFilter
from retro_data_structures.properties.prime_remastered.objects.RelayProbabilityGameMode import RelayProbabilityGameMode
from retro_data_structures.properties.prime_remastered.objects.RelayRandom import RelayRandom
from retro_data_structures.properties.prime_remastered.objects.ReloadSetLoader import ReloadSetLoader
from retro_data_structures.properties.prime_remastered.objects.Render import Render
from retro_data_structures.properties.prime_remastered.objects.RenderClipPlane import RenderClipPlane
from retro_data_structures.properties.prime_remastered.objects.RenderDecal import RenderDecal
from retro_data_structures.properties.prime_remastered.objects.RenderGroup import RenderGroup
from retro_data_structures.properties.prime_remastered.objects.RenderWorld import RenderWorld
from retro_data_structures.properties.prime_remastered.objects.ResetObject import ResetObject
from retro_data_structures.properties.prime_remastered.objects.Respawn import Respawn
from retro_data_structures.properties.prime_remastered.objects.Retronome import Retronome
from retro_data_structures.properties.prime_remastered.objects.RetronomeDriver import RetronomeDriver
from retro_data_structures.properties.prime_remastered.objects.ReverbFieldNode import ReverbFieldNode
from retro_data_structures.properties.prime_remastered.objects.RhythmMatcher import RhythmMatcher
from retro_data_structures.properties.prime_remastered.objects.RoomController import RoomController
from retro_data_structures.properties.prime_remastered.objects.RoomPreloader import RoomPreloader
from retro_data_structures.properties.prime_remastered.objects.RoomSettings import RoomSettings
from retro_data_structures.properties.prime_remastered.objects.RuleSetManager import RuleSetManager
from retro_data_structures.properties.prime_remastered.objects.RumbleEffectsDefinition import RumbleEffectsDefinition
from retro_data_structures.properties.prime_remastered.objects.RumbleEmitter import RumbleEmitter
from retro_data_structures.properties.prime_remastered.objects.RumbleSensoryDefinition import RumbleSensoryDefinition
from retro_data_structures.properties.prime_remastered.objects.SampleBankData import SampleBankData
from retro_data_structures.properties.prime_remastered.objects.SampleBankHint import SampleBankHint
from retro_data_structures.properties.prime_remastered.objects.SamplerVoiceBankData import SamplerVoiceBankData
from retro_data_structures.properties.prime_remastered.objects.SaveSlot import SaveSlot
from retro_data_structures.properties.prime_remastered.objects.Scannable import Scannable
from retro_data_structures.properties.prime_remastered.objects.ScorableTarget import ScorableTarget
from retro_data_structures.properties.prime_remastered.objects.Scoring import Scoring
from retro_data_structures.properties.prime_remastered.objects.ScreenCoverageTrigger import ScreenCoverageTrigger
from retro_data_structures.properties.prime_remastered.objects.ScreenShot import ScreenShot
from retro_data_structures.properties.prime_remastered.objects.ScreenSpaceAO import ScreenSpaceAO
from retro_data_structures.properties.prime_remastered.objects.ScriptedAnimationData import ScriptedAnimationData
from retro_data_structures.properties.prime_remastered.objects.ScriptedJumpData import ScriptedJumpData
from retro_data_structures.properties.prime_remastered.objects.ScriptedMotion import ScriptedMotion
from retro_data_structures.properties.prime_remastered.objects.ScriptedMotionPhaseResponder import (
    ScriptedMotionPhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.SetAnimVisibilityState import SetAnimVisibilityState
from retro_data_structures.properties.prime_remastered.objects.SetInventory import SetInventory
from retro_data_structures.properties.prime_remastered.objects.SettingsMenuManager import SettingsMenuManager
from retro_data_structures.properties.prime_remastered.objects.ShockWave import ShockWave
from retro_data_structures.properties.prime_remastered.objects.SimpleShadow import SimpleShadow
from retro_data_structures.properties.prime_remastered.objects.SimpleSound import SimpleSound
from retro_data_structures.properties.prime_remastered.objects.SimpleSoundPhaseResponder import (
    SimpleSoundPhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.SkinSwap import SkinSwap
from retro_data_structures.properties.prime_remastered.objects.Skybox import Skybox
from retro_data_structures.properties.prime_remastered.objects.SlideShow import SlideShow
from retro_data_structures.properties.prime_remastered.objects.SnapToPath import SnapToPath
from retro_data_structures.properties.prime_remastered.objects.SniperPoint import SniperPoint
from retro_data_structures.properties.prime_remastered.objects.Sound import Sound
from retro_data_structures.properties.prime_remastered.objects.SoundFilterModifier import SoundFilterModifier
from retro_data_structures.properties.prime_remastered.objects.SoundLevelMeterPhaseDriver import (
    SoundLevelMeterPhaseDriver,
)
from retro_data_structures.properties.prime_remastered.objects.SoundPitchModifier import SoundPitchModifier
from retro_data_structures.properties.prime_remastered.objects.SoundVolumeModifier import SoundVolumeModifier
from retro_data_structures.properties.prime_remastered.objects.SpawnPoint import SpawnPoint
from retro_data_structures.properties.prime_remastered.objects.SplineMotion import SplineMotion
from retro_data_structures.properties.prime_remastered.objects.SplineMotionPhaseResponder import (
    SplineMotionPhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.StaticCollision import StaticCollision
from retro_data_structures.properties.prime_remastered.objects.Steering import Steering
from retro_data_structures.properties.prime_remastered.objects.StreamedMovie import StreamedMovie
from retro_data_structures.properties.prime_remastered.objects.SubtitleSequence import SubtitleSequence
from retro_data_structures.properties.prime_remastered.objects.SurfaceControl import SurfaceControl
from retro_data_structures.properties.prime_remastered.objects.SurfaceGenerator import SurfaceGenerator
from retro_data_structures.properties.prime_remastered.objects.TakeDamage import TakeDamage
from retro_data_structures.properties.prime_remastered.objects.TemplateManager import TemplateManager
from retro_data_structures.properties.prime_remastered.objects.Terrain import Terrain
from retro_data_structures.properties.prime_remastered.objects.TerrainAlignment import TerrainAlignment
from retro_data_structures.properties.prime_remastered.objects.TextPane import TextPane
from retro_data_structures.properties.prime_remastered.objects.TimeDilation import TimeDilation
from retro_data_structures.properties.prime_remastered.objects.TimeKeyframe import TimeKeyframe
from retro_data_structures.properties.prime_remastered.objects.Timer import Timer
from retro_data_structures.properties.prime_remastered.objects.TimerAnimationGridParamProvider import (
    TimerAnimationGridParamProvider,
)
from retro_data_structures.properties.prime_remastered.objects.TimerProgression import TimerProgression
from retro_data_structures.properties.prime_remastered.objects.TimerSequence import TimerSequence
from retro_data_structures.properties.prime_remastered.objects.TimerSequencePhaseResponder import (
    TimerSequencePhaseResponder,
)
from retro_data_structures.properties.prime_remastered.objects.TimerStopwatch import TimerStopwatch
from retro_data_structures.properties.prime_remastered.objects.Tippy import Tippy
from retro_data_structures.properties.prime_remastered.objects.ToneData import ToneData
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorHint import ToneSelectorHint
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorMIDI import ToneSelectorMIDI
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorScriptDriven import ToneSelectorScriptDriven
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorSequence import ToneSelectorSequence
from retro_data_structures.properties.prime_remastered.objects.Tonemap import Tonemap
from retro_data_structures.properties.prime_remastered.objects.Touch import Touch
from retro_data_structures.properties.prime_remastered.objects.TouchSet import TouchSet
from retro_data_structures.properties.prime_remastered.objects.TouchableTrigger import TouchableTrigger
from retro_data_structures.properties.prime_remastered.objects.TriggerDamage import TriggerDamage
from retro_data_structures.properties.prime_remastered.objects.TriggerDeathFall import TriggerDeathFall
from retro_data_structures.properties.prime_remastered.objects.TriggerForce import TriggerForce
from retro_data_structures.properties.prime_remastered.objects.TriggerInhabitant import TriggerInhabitant
from retro_data_structures.properties.prime_remastered.objects.TriggerLogic import TriggerLogic
from retro_data_structures.properties.prime_remastered.objects.TriggerProgressionVolume import TriggerProgressionVolume
from retro_data_structures.properties.prime_remastered.objects.UIButton import UIButton
from retro_data_structures.properties.prime_remastered.objects.UICamera import UICamera
from retro_data_structures.properties.prime_remastered.objects.UIListView import UIListView
from retro_data_structures.properties.prime_remastered.objects.UIMenu import UIMenu
from retro_data_structures.properties.prime_remastered.objects.UIProxy import UIProxy
from retro_data_structures.properties.prime_remastered.objects.UIRelay import UIRelay
from retro_data_structures.properties.prime_remastered.objects.UISlider import UISlider
from retro_data_structures.properties.prime_remastered.objects.UIWidget import UIWidget
from retro_data_structures.properties.prime_remastered.objects.UVTransform import UVTransform
from retro_data_structures.properties.prime_remastered.objects.VoiceEffect import VoiceEffect
from retro_data_structures.properties.prime_remastered.objects.VolumetricFog import VolumetricFog
from retro_data_structures.properties.prime_remastered.objects.VolumetricFogHint import VolumetricFogHint
from retro_data_structures.properties.prime_remastered.objects.VolumetricFogRegion import VolumetricFogRegion
from retro_data_structures.properties.prime_remastered.objects.VolumetricFogRegionTransition import (
    VolumetricFogRegionTransition,
)
from retro_data_structures.properties.prime_remastered.objects.WanderPoint import WanderPoint
from retro_data_structures.properties.prime_remastered.objects.WaterRenderVolume import WaterRenderVolume
from retro_data_structures.properties.prime_remastered.objects.Waypoint import Waypoint
from retro_data_structures.properties.prime_remastered.objects.WindWaker import WindWaker
from retro_data_structures.properties.prime_remastered.objects.WorldTransition import WorldTransition

if typing.TYPE_CHECKING:
    from retro_data_structures.properties.base_property import BaseProperty

_FOUR_CC_MAPPING: dict[int, type[BaseProperty]] = {
    0xB6200BE6: ActorMP1,
    0xA856F484: ColorModulateMP1,
    0x32AEF7DD: CounterMP1,
    0x59BC6B3B: DebugActorMP1,
    0x8E4C86EC: WaypointMP1,
    0x99EA4919: PlayerMP1,
    0x79F02E11: SpawnPointMP1,
    0x7003C6AA: EnergyProjectileMP1,
    0x42A7692D: ControllerActionMP1,
    0xF5CE0E14: PlasmaProjectileMP1,
    0xE9F08E02: BombMP1,
    0xD62862CA: PowerBombMP1,
    0x2CA49DE4: NewFlameThrowerMP1,
    0x7191E814: WaveBusterMP1,
    0x50E62AE4: ExplosionMP1,
    0x2CB074D1: ShockWaveMP1,
    0x618B3777: FlameThrowerMP1,
    0xB130AB71: IceAttackProjectileMP1,
    0xDAF49AD2: DamageEffectMP1,
    0x7059AA54: CollisionActorMP1,
    0x1B78F9A4: ScriptRelayMP1,
    0x25C6D2A3: TimerMP1,
    0xF526FC2A: TriggerMP1,
    0xC0E28B3D: SwitchMP1,
    0xEFA09DB4: AiJumpPointMP1,
    0xA7C1E08D: RumbleEffectMP1,
    0x3CE6630A: ActorKeyframeMP1,
    0xFC64463E: SteamMP1,
    0x50F2F67A: BallTriggerMP1,
    0x1FAB791D: FirstPersonCameraMP1,
    0x76A6385F: BallCameraMP1,
    0x04E9F22E: FreeCameraMP1,
    0xE44D80F3: InterpolationCameraMP1,
    0x71337F4F: SpecialFunctionMP1,
    0xA497918D: AmbientAIMP1,
    0x3391E02B: ActorRotateMP1,
    0x1205609A: MemoryRelayMP1,
    0xA12967FB: PlatformMP1,
    0xB421CDCB: EffectMP1,
    0x77E59F98: HUDMemoMP1,
    0xDCB49607: DamageableTriggerMP1,
    0x12DB855D: WaterMP1,
    0xB0C4378E: MagdoliteMP1,
    0xFE939195: JellyZapMP1,
    0xB6E36FD4: WarWaspMP1,
    0xCBE62855: IceSheegothMP1,
    0xE8CA3EA0: GarBeetleMP1,
    0x1A03F50A: FlickerBatMP1,
    0xBE462B0E: ParasiteMP1,
    0xDB9430C7: FlaahgraRendererMP1Runtime,
    0xD2806770: FlaahgraPlantsMP1Runtime,
    0x0FFFBA0C: FlaahgraProjectileMP1Runtime,
    0x30A6B6DE: FlaahgraTentacleMP1,
    0x3C669ACB: FlaahgraMP1,
    0x52EBC2A7: FireFleaMP1,
    0xC963CC17: EyeBallMP1,
    0x242C3C90: PuddleSporeMP1,
    0x7F2845C7: OmegaPirateMP1,
    0xF4326A02: ElitePirateMP1,
    0x0EB1F342: SpacePirateMP1,
    0x50B7576D: DroneMP1,
    0x84B92D36: ChozoGhostMP1,
    0x1C3D435D: BurrowerMP1,
    0x6CFA6902: FlyingPirateMP1,
    0x4DEB1E3A: BloodFlowerMP1,
    0x1498BA74: TryclopsMP1,
    0x254D4D49: BabygothMP1,
    0x4F9D71EC: RidleyMP1,
    0xF800EFF9: BouncyGrenadeMP1,
    0xADA0EC66: PufferMP1,
    0x09EAF010: OculusMP1,
    0xB99D2B06: GeemerMP1,
    0x87412090: AtomicBetaMP1,
    0x61653ED2: AtomicAlphaMP1,
    0x2249224E: AThardusRockProjectileMP1,
    0xEAA40B01: ThardusMP1,
    0x7A4BC122: WorldLightFaderMP1,
    0x17DB2246: ShadowProjectorMP1,
    0x705B28FC: SpankWeedMP1,
    0x36B8D0D0: SpindleCameraMP1,
    0x33D9FFA6: ThermalHeatFaderMP1,
    0xC30C5758: TeamAiMgrMP1,
    0x3AB7170D: RippleMP1,
    0x65EE9092: IntroBossMP1,
    0x48AE7CA9: TargetingPointMP1,
    0xC7668E15: SpiderBallWaypointMP1,
    0xD4CD5E63: SpiderBallAttractionSurfaceMP1,
    0xACC3CE1E: PhazonPoolMP1,
    0x93C5B36D: RadialDamageMP1,
    0x02EAEC98: CameraMP1,
    0x2B3AD4B6: CoverPointMP1,
    0xC6E2DE1F: PathCameraMP1,
    0x47E5D68B: MazeNodeMP1,
    0x4CA59EB7: PickupGeneratorMP1,
    0x176F6F27: CameraPitchVolumeMP1,
    0x7D070EF0: ElectroMagneticPulseMP1,
    0x3C832EC7: EnvFxDensityControllerMP1,
    0x8BEDB563: VisorFlareMP1,
    0xAD191C7E: CameraHintMP1,
    0x2131945E: DistanceFogMP1,
    0x16B8B319: WallCrawlerSwarmMP1,
    0x8EE5D87E: GeneratorMP1,
    0x4CA870EF: CameraHintTriggerMP1,
    0x1704C1F0: GunTurretMP1,
    0x23F1E994: PlayerHintMP1,
    0x6665F6DF: DebrisExtendedMP1,
    0xCD695064: RoomAcousticsMP1,
    0x564A1641: DoorMP1,
    0xB5CD58CD: ContraptionMP1,
    0x0EB82E3B: GrapplePointMP1,
    0x36386A69: PickupMP1,
    0x03168FE6: NotSTD_DockMP1,
    0xDF4FCCA3: RandomRelayMP1,
    0x0E7A0171: DebrisMP1,
    0x99DFC912: CameraShakerNewMP1,
    0x9B0F9C29: CameraShakerOldMP1,
    0xCB5682C4: VisorGooMP1,
    0x3BAB18A0: MidiMP1,
    0x46787DDD: SoundMP1,
    0x7E1F2807: StreamedAudioMP1,
    0x750702EA: CameraFilterKeyframeMP1,
    0x2FA104FF: WorldTeleporterTooMP1,
    0xCC92B31B: CameraBlurKeyframeMP1,
    0x0D5C1882: PointOfInterestMP1,
    0x48F8341D: AreaAttributesMP1,
    0xF649EEC3: CameraWaypointMP1,
    0xDB389155: PlayerActorMP1,
    0x1230FA75: MetareeMP1,
    0x55032CDA: MetroidBetaMP1,
    0x0B6B2691: SeedlingMP1,
    0xBCF96C94: TargetableProjectileMP1,
    0xB5D157DB: RipperMP1,
    0xAC1C4AAD: SnakeWeedSwarmMP1,
    0x7FC7DEBC: MetroidMP1,
    0x719EE8C2: PuddleToadGammaMP1,
    0x41BC06DD: FishCloudModifierMP1,
    0x622F6B23: MetroidPrimeRelayMP1,
    0x5048D44F: GrapplePointMP1Runtime,
    0xD909C936: ControlledPlatformMP1Runtime,
    0x4E8A3CE2: FishCloudMP1,
    0xA68D2EB5: PhazonHealingNoduleMP1,
    0xAE757B71: MetroidPrimeMP1,
    0x5797D3C7: ProxyPlayerMP1,
    0x980EF312: MetroidPrimeStage2MP1,
    0x9B592020: VisorFlareMP1Runtime,
    0xD39988C0: DroneLaserMP1Runtime,
    0xDCF9614B: DeathCameraEffectMP1Runtime,
    0x27116D98: ElitePirateGrenadeLauncherMP1Runtime,
    0x7CF4C8C0: PoisonProjectileMP1,
    0x1E3517FC: MissileTargetMP1,
    0x42020DA4: DestroyableRockMP1Runtime,
    0x6EA08BAD: RoomOcclusionOverrideMP1,
    0x82980E58: ElectricBeamProjectileMP1Runtime,
    0xE5740BFD: CameraOverrideMP1,
    0xCB3B5BEA: AnimatedCameraMP1,
    0x85E5E721: ARepulsorMP1,
    0x90905F24: PlayerStateChangeMP1,
    0xAE09E5E2: AEnergyBallMP1,
    0x0515541D: AScriptBeamMP1,
    0xEB70CD36: SustainedPlayerDamageMP1Runtime,
    0x104A7116: HUDManagerMP1,
    0x7383D6B5: ScriptHUDBillboardEffectMP1,
    0x333F83D4: RumbleEventResponderMP1,
    0x14D107FE: CinematicStateProxyMP1,
    0x63B6ECDC: HUDBillboardFreezeEffectTestMP1,
    0xC1FAC87D: ScriptedOcclusionVolumeMP1,
    0x8A12A2F9: MaterialVariableDriverMP1,
    0xE12AAE70: EffectProxyMP1,
    0xF06785E1: CinematicMP1,
    0x73A6D8F1: PhazonDriverMP1,
    0x55A188F6: AmbientParticleEffectPrimitiveShapeProviderMP1,
    0x98EEA4CA: XRayHintMP1,
    0x6A7A53B0: CameraWaterStateProxyMP1,
    0xDF22BD66: WaterTransitionMP1,
    0x08B8689D: AreaOcclusionModifierMP1,
    0x9FEAB9B3: BakedLightingPriorityModifierMP1,
    0x451C85B6: AutoExposureHintMP1,
    0x427C6C50: ActorIceDarkenerMP1,
    0xD09FBBE7: AABoxMagnet,
    0xAC073DF4: AIGenerator,
    0x55960D16: AIGeneratorSelector,
    0x71A1C997: AIPostOwner,
    0x41AD2545: AITeleportProxy,
    0xE795D2B1: ActionControlPoint,
    0xB4361E7B: ActorCollision,
    0xC7B43DA6: ActorInteraction,
    0x1FB9AF22: ActorKeyframe,
    0x35FA03A6: ActorKeyframePhaseResponder,
    0x412E0D82: ActorVertexAnimationPhaseResponder,
    0x75560CE3: ActorVertexAnimationPlayList,
    0x5CF17BFE: AdapterManager,
    0xD813A35A: AddActorEntityFlag,
    0x9E20D0AF: AiTarget,
    0x088E7782: AiTargetManager,
    0xCBE2042D: AmbientParticleEffect,
    0xDEC78ECB: AnalogDriver,
    0x044ED3D2: AnchorPoint,
    0xDAE5D368: AngleCompare,
    0xD34AB306: AnimVisibilityStateGroupManager,
    0xAD2098FA: AnimatedMeter,
    0xE493532F: AnimatedMeterPhaseResponder,
    0xD8726471: AnimatedSprite,
    0xBCA078F7: AnimationController,
    0xC3CCC605: AnimationEventListener,
    0x2751EBF2: AnimationGridController,
    0x5453C979: AnimationMountRider,
    0xEB5B364D: AnimationPlaybackRate,
    0x97947F1E: AnimationRateModifier,
    0x917FD37D: AnimationUserEventRouter,
    0x1F8CA08E: AnimationVariableReal,
    0x3175DF36: ApplyDamage,
    0x3DA7DA05: AttackManager,
    0x6ACAA7DA: AttackManagerTest,
    0x655C5175: AudioBusController,
    0xD515E89D: AudioBusDriver,
    0x2C9918AE: AudioBusDriverInteractor,
    0x62913993: AudioBusMixer,
    0x62C5D8C7: AudioBusPhaseResponder,
    0xEEA718B9: AudioEmitter,
    0xECE8E32E: AudioObstruction,
    0x135C010E: AudioObstructionOcclusionOverride,
    0xC3049839: AudioOcclusionVolume,
    0xF6559CEA: AudioOutputEffects,
    0x57312ED0: AudioPluginEffect,
    0x8E881C85: AudioPluginEffectCrossfadePhaseResponder,
    0xC5BFD655: AudioPluginEffectCrossfadeSend,
    0x17982019: AudioSampleBank,
    0xDC777C06: AudioSampler,
    0xD54B0DCC: AudioSamplerPhaseResponder,
    0xFC397B56: AudioSamplerProxy,
    0x98694074: AutoExposureHint,
    0x5CB0DE9C: BGMHint,
    0x190D20D7: Backlight,
    0x392DCDF1: Beam,
    0xA41FC3A9: BlackboardBoolean,
    0xC8A56ECC: BlackboardBooleanWriter,
    0x25E4D42F: BlackboardPhaseRelay,
    0xBFB2C3AE: BlackboardPhaseRelayWriter,
    0x13D0F71D: BlackboardRealNumber,
    0x12A1D49F: BlackboardRealNumberWriter,
    0x7DCAF170: BloomEffect,
    0xF66B9100: BloomEffectHint,
    0xDE3024E9: BoolToRealMap,
    0x05DD288E: Boolean,
    0x854924D1: BoostPad,
    0xD4AC7206: BossMeterState,
    0x62FC6E51: BroadcastAudioEvent,
    0x458501CF: BroadcastAudioEventListener,
    0xA482E214: BroadcastGlobal,
    0x3E9F6170: BroadcastGlobalListener,
    0x9AAFCB03: BroadcastSpatial,
    0x0EF9ABE4: BroadcastSpatialListener,
    0x8666855A: CameraAdditiveFOV,
    0xB0C9B2F9: CameraFilter,
    0x4FE57689: CameraHint,
    0x945E0902: CameraLetterBox,
    0xBC9A60AE: CameraManager,
    0xC16B7565: CameraPointOfInterest,
    0x514043DD: CameraPredictivePitchHint,
    0x322F85E1: CameraPredictiveYawHint,
    0x5E3F39EE: CameraProxy,
    0x343A47F7: CameraShaker,
    0x59372FE6: CameraSystemHint,
    0xC1F64515: CameraTarget,
    0x09E806C4: CameraTargetCreature,
    0x78D8893A: CameraTargetPlayer,
    0x2BC6608A: CameraTargetProxy,
    0xA7D1C922: CausticVolume,
    0x6027B2CE: ChainLightning,
    0x6548CFCC: CharacterPrimitives,
    0x591D8F55: CharacterPrimitivesCollision,
    0x660FC7C1: Checkpoint,
    0x8CE59F27: Choreographer,
    0x2B854B47: ChromaticAberration,
    0xC9EEBC83: Cinematic,
    0xD298FC35: CinematicActor,
    0x89F426F2: CinematicCameraShot,
    0x55F80CCE: CinematicSkipHandler,
    0x00536567: CollisionAvoidanceManager,
    0x4368E960: CollisionLogic,
    0xA3B90913: CollisionProbe,
    0x27568F71: CollisionWithWorld,
    0x6B091E44: ColorGrade,
    0xA36CD908: ColorGradeHint,
    0xB85D6790: ColorModifier,
    0x12931CE3: ColorSampler,
    0x1A4BC6BD: CombatStateProxy,
    0x76025BB8: Condition,
    0x59CFBBD7: ContextInteraction,
    0x29B7E32A: ControlCommandDisabler,
    0x66AD5099: ControlCommandMappingAdd,
    0xAC392770: ControlCommandMappingAnd,
    0xDAEE1AAD: ControlCommandMappingDebugMenuBoolean,
    0xCC5AE725: ControlCommandMappingDebugMenuInt,
    0xAB505EAB: ControlCommandMappingDebugMenuRealEvaluator,
    0x8B123910: ControlCommandMappingDebugMenuRealMultiplier,
    0xEE0426D8: ControlCommandMappingMultiply,
    0x571F8FD2: ControlCommandMappingNegate,
    0x7B8DB9C7: ControlCommandMappingNegativeOne,
    0xECDCE2E3: ControlCommandMappingNode,
    0xDB4AB61D: ControlCommandMappingNot,
    0x98AACF09: ControlCommandMappingOne,
    0x81EC3BB6: ControlCommandMappingOr,
    0x65823457: ControlCommandMappingPhysical,
    0x0E33F78B: ControlCommandMappingScriptedReal,
    0x94147BD8: ControlCommandMappingSpline,
    0x48C1CEF7: ControlCommandMappingZero,
    0x7CDFBC83: ControlCommandMappingsDefinition,
    0xF0D1BCC7: ControlCommandSpoofer,
    0x60E107E0: ControlSchemeAccessor,
    0x0637E29A: ControlSchemesDefinition,
    0x00682591: ControlSplineMappingsDefinition,
    0xD616EE8B: ControllerAction,
    0xB7332353: ControllerAnalogInputDriver,
    0xC6F6F28C: ControllerAnalogMovement,
    0x0998FFC9: ControllerAnalogShapeAction,
    0xAE579212: ControllerMotionDriver,
    0x1EB2749F: ConveyorModifier,
    0xA7DB53C1: Counter,
    0x4812E080: CounterAdapter,
    0x47E7EE64: CounterPhaseResponder,
    0xC0366DC7: CoverPoint,
    0xA3FE9467: CreatureActionBroadcaster,
    0xA619D230: CreatureActionPatternBehavior,
    0x87CF06DF: CreatureAiming,
    0x6B3CDB28: CreatureAmbushBehavior,
    0x1F969D66: CreatureArmor,
    0xF3133CDF: CreatureAttackPathBehavior,
    0x986AD9EA: CreatureBase,
    0x97422C3F: CreatureChangePostureBehavior,
    0x444959AD: CreatureCollisionAvoidance,
    0x931B692F: CreatureContextInteraction,
    0x81718106: CreatureContextInteractionBehavior,
    0x9E73EB5D: CreatureCoverCombatBehavior,
    0x949E5BBE: CreatureDeployActionBehavior,
    0x52BFD9AD: CreatureDespawnBehavior,
    0xC062FD1A: CreatureEvadeBehavior,
    0x01B1EBDD: CreatureFallBehavior,
    0x5904644C: CreatureFireDamage,
    0x2AB5EF6F: CreatureFleeBehavior,
    0x874AA246: CreatureFlinch,
    0xF33FD0C8: CreatureGrabTarget,
    0xDB0310B9: CreatureHeadTracking,
    0x81519976: CreatureHealth,
    0x2E8A5117: CreatureHecklerBehavior,
    0xCDB24FAD: CreatureHitReactionBehavior,
    0xCF272BD6: CreatureHurlBehavior,
    0x86692789: CreatureIceDamage,
    0xE9B9F6EE: CreatureLeashBehavior,
    0x45924F80: CreatureMeleeCombatBehavior,
    0xA60A6693: CreatureMovement,
    0x228A335D: CreatureNavigateBehavior,
    0xFC76D74C: CreaturePatrolBehavior,
    0x2A7E80CC: CreaturePositionLogic_WaypointScripting,
    0xD5DCB013: CreaturePositioning,
    0x5BA03233: CreaturePositioningManager,
    0xDE991E1E: CreatureProjectileLauncher,
    0xD36B0797: CreatureProneBehavior,
    0x834CF41D: CreatureRangedCombatBehavior,
    0x4A8D8E14: CreatureRules,
    0xFC7D9A11: CreatureScriptedActionBehavior,
    0x0ABE969D: CreatureScriptedAnimationBehavior,
    0x51422A18: CreatureScriptedJumpBehavior,
    0xD1BBF0E7: CreatureSecondaryActions,
    0x16169AEA: CreatureSecondaryAnimation,
    0xD8A9F583: CreatureSniperBehavior,
    0xC1C02476: CreatureSpawnBehavior,
    0xFB26FD7D: CreatureSplineFollowBehavior,
    0xEFED81F1: CreatureTargetable,
    0x2095A979: CreatureTargeting,
    0xD73EBB11: CreatureThunderDamage,
    0x8BB84EB1: CreatureTurnBehavior,
    0x7FCBC2AD: CreatureTurnProcedural,
    0xA38743D1: CreatureWaitAtPositionBehavior,
    0x24EB1A32: CreatureWanderBehavior,
    0xA60583CC: Credits,
    0x1349E5AC: CustomInterpolation,
    0xF7602744: DSP,
    0x75C4E493: DamageRelay,
    0x736DD919: DamageResponderVulnerability,
    0x5A82703D: DebugMenuItemsDefinition,
    0x69091B92: DetectionPlane,
    0x46033F8D: DistanceCompare,
    0x9F61CD7F: DistanceCompareGroup,
    0xA10BAA67: Dock,
    0xAE371A20: DockDoor,
    0x244019EB: Drivable,
    0x21C57D2B: DynamicActorCollision,
    0x5746A908: DynamicActorControl,
    0x40F9629D: DynamicControlScriptedRealDefinition,
    0xEE0D6FD4: DynamicLoadManager,
    0xCD098F70: Effect,
    0xFD5075F3: EffectVariableDriver,
    0x18C0AD0F: EndGame,
    0x749749F1: EntityProperties,
    0x69504ACB: EnumToRealMap,
    0x528C1159: Enumeration,
    0x2F0C8179: EnvironmentVarListener,
    0xF05BC9C3: EnvironmentVarModifier,
    0x4C183EBB: EnvironmentVarQuery,
    0xC26ABE1A: EnvironmentVarSender,
    0x021C14B0: Explosion,
    0x8F6C4769: FSMController,
    0x002CE325: FSMHotSwapper,
    0x8832EA4D: FSMManager,
    0x7C9B685C: FSMMessage,
    0xAFD50F72: Faction,
    0x3BBBE401: FactionManager,
    0x4EC5FA3A: FakePlayerControls,
    0x0C55DC4E: FleePoint,
    0xF9F62FD4: FlowPath,
    0x92561A4A: FogShape,
    0x73AECD92: FogVolume,
    0x74BD547A: Footprint,
    0x8F472283: FrontEndManager,
    0x46B12081: GameFlowHub,
    0x10BE69F9: GameFlowProxy,
    0x70292D3D: GameFlowRelay,
    0xA190EAA2: GameOptionsAccessor,
    0xB28E4996: GameOptionsDefinition,
    0xEA33D242: GameVariableAccess,
    0xDE522669: Generator,
    0xFA73D359: GenericAimTarget,
    0xCC8F9FF2: GenericSplineControl,
    0x6221A411: GibManager,
    0xECD265D2: GlobalStateMonitor,
    0x87EFBCF0: GradientAmbient,
    0xD745DC42: GraphicalTransition,
    0x2131C235: GroupSpawn,
    0xA02CF18F: HUDSuppressor,
    0xEA6D58E8: HardwareProxy,
    0x06E89BE7: Health,
    0x7E394FF2: HealthDisplay,
    0xAD67F77F: HealthDisplaySource,
    0xE7C5BA34: HealthPhases,
    0xD008829F: HeatDistortionHint,
    0x3A080954: HeightfieldSurfaceDescription,
    0xC0281AE7: ImpulseDriver,
    0x1955E30C: IncandescenceModulator,
    0x6467B289: InputMacroPlayer,
    0x83EB0628: InputMacroRecorder,
    0x8C9B8856: IntToRealMap,
    0x24D8FDD0: InventoryInitializer,
    0xF34EDD1F: InventoryItem,
    0x79738030: InventoryTextPane,
    0x78ADD45F: Label,
    0xF75EA7EF: LavaFlowSurface,
    0xA7EE9C33: LavaRenderVolume,
    0xBD040603: LevelDarkener,
    0x9EE5541D: LightDynamic,
    0xD2CAC9A5: LightGroupProxy,
    0x56CF02A6: LightHint,
    0x37E758DA: LightShafts,
    0x2BE8BC19: LightStatic,
    0xB1A9ECED: LineOfSight,
    0x3449A5DF: LiquidInhabitant,
    0xE1E1C49C: LiquidVolume,
    0x4C53A836: LoadUnitController,
    0x9340932C: LogicGate,
    0x9D97D9C1: MIDIControllerMessageEmitter,
    0x2249DE78: MIDIMatcher,
    0x84BB17FA: MIDINoteAdaptor,
    0x4CA2E586: MIDINoteEmitter,
    0x4F10BECB: MIDIReceiver,
    0xD9C9A3F5: MIDIResponderArpeggiator,
    0xBA249E78: MIDIResponderChordMaker,
    0x11F81321: MIDIResponderPatternMatcher,
    0xF12E9C71: MIDIResponderSampler,
    0x76AAC155: MIDIRetronome,
    0x18E10190: MIDISequence,
    0xE6A64862: MIDITransmitter,
    0x451740EB: ModCon,
    0x25899782: MusicData,
    0x1AC8C8FD: MusicStateController,
    0xA86001C4: MusicStateTransitionData,
    0x47A60DC3: MusicSystemTransport,
    0x676A5AC4: NavigationAreaLink,
    0x49BD721E: NavigationMesh,
    0xF190A097: NavigationMeshDock,
    0x3536E079: NavigationMeshDynamicObstruction,
    0x4490513E: NavigationMeshHint,
    0x20C7601E: NavigationMeshIncludeExcludeHint,
    0x85298BEA: NavigationOffMeshLink,
    0xCE69684B: NavigationPathPoint,
    0x37B90174: NavigationPathPointOffMeshLink,
    0x6C5D597D: NearVisible,
    0x10EA9EC8: ObjectFollow,
    0xED02DE02: ObjectSelector,
    0xE1C825C9: ObjectTeleport,
    0xF6A30345: Occlusion,
    0xCEAFD99C: OrbitTarget,
    0x9E219714: OriginatorProxy,
    0x5B5FB670: POIRoomController,
    0x3FCF5A88: ParticleVolume,
    0xF0240D23: PathControl,
    0xD0368513: PathFind,
    0xB3B55602: PathGenerator,
    0x1A828893: PathMovement,
    0x9C7DF587: PathMovementMagnetizationPoint,
    0xDF279C9B: PatternMatcher,
    0xCCAD4BD9: PerformanceGroupController,
    0x6F5A20BE: PerformanceHint,
    0xB793D90A: PeriodicAdditiveAnimationDriver,
    0xB9FAC2DF: PhaseCombinator,
    0x8CE6E4F6: PhaseLooper,
    0xC04D4753: PhaseRelay,
    0x00921362: PhaseToEvents,
    0x0A3B4FD2: PhysicsDriver,
    0x481EA5AF: Pickup,
    0x720A3AC5: PickupDropper,
    0x057DC20F: PickupManager,
    0x7E6063C8: PlayerActor,
    0xCBA2FC47: PlayerDeathFall,
    0xF06BBE92: PlayerEventListener,
    0xC338FD04: PlayerInventoryEffects,
    0xF6751A5D: PlayerKeyframe,
    0x8C2CCFAC: PlayerRespawn,
    0x7FAE7590: PlayerRoomTeleporter,
    0xCE2470CB: PlayerSpawnPoint_InputMacroRelay,
    0x916F072F: PlayerSpawnTeleporter,
    0x238467F5: PlayerTeleport,
    0xBA796FEF: Playlist,
    0xCE22001E: PoiObject,
    0xAFB53A8C: PointOfInterest,
    0x414D77FF: ProjectedShadowBlob,
    0x1243C3E3: ProjectedSimpleShadowReceiver,
    0xB692D28B: Projectile,
    0xFDA2465A: ProjectileIntersectionHint,
    0x6654CA01: ProxyRegisteredEntity,
    0xF75ADD4D: Reactivator,
    0xD855B36E: RealNumber,
    0xBC121D69: RealNumberComparison,
    0xD81EF16F: RealNumberDriver,
    0x2CDAF986: RealNumberFunction,
    0x3713FD4F: RealNumberPhaseResponder,
    0xECFFB88F: RealToRealMap,
    0x63DD6841: RealValueRelay,
    0x27807E39: ReflectionProbe,
    0xCB54E84D: RegisterEntity,
    0x8FE0BFC9: Relay,
    0xF20F2698: RelayAttackTypePayload,
    0x7F6D1CBA: RelayAutoFire,
    0xD7C7E6F9: RelayChoreography,
    0xABBCFC6A: RelayConditional,
    0x455285E2: RelayFrameDelay,
    0x91C301A5: RelayMemory,
    0x5959DB91: RelayOriginatorFilter,
    0xB6040870: RelayProbabilityGameMode,
    0x65E2349B: RelayRandom,
    0x16702F15: ReloadSetLoader,
    0xDF31EC16: Render,
    0x21A978D3: RenderClipPlane,
    0xD7B10EFD: RenderDecal,
    0xA72A9926: RenderGroup,
    0x41956904: RenderWorld,
    0x7DB10F4C: ResetObject,
    0x9373FEC0: Respawn,
    0x845E492A: Retronome,
    0x0FA3899C: RetronomeDriver,
    0x712755E8: ReverbFieldNode,
    0x3DFD89F7: RhythmMatcher,
    0x83CC17AA: RoomController,
    0xB2DA6936: RoomPreloader,
    0x160E9AF9: RoomSettings,
    0x3325A532: RuleSetManager,
    0x12D9053F: RumbleEffectsDefinition,
    0x224F782C: RumbleEmitter,
    0x1F0AFAB0: RumbleSensoryDefinition,
    0x8BE6648A: SampleBankData,
    0xCF9E2373: SampleBankHint,
    0x61EF47C6: SamplerVoiceBankData,
    0x8B306E38: SaveSlot,
    0x157533DD: Scannable,
    0x3254E042: ScorableTarget,
    0x7D3512D7: Scoring,
    0x12C9E761: ScreenCoverageTrigger,
    0x0D3E0D14: ScreenShot,
    0x8061E045: ScreenSpaceAO,
    0x80B94FCD: ScriptedAnimationData,
    0x331613D1: ScriptedJumpData,
    0xF78649C8: ScriptedMotion,
    0x50B4F3D7: ScriptedMotionPhaseResponder,
    0xD2BCB71A: SetAnimVisibilityState,
    0x7A38CC26: SetInventory,
    0x91666769: SettingsMenuManager,
    0xCD85A847: ShockWave,
    0x212BCDF5: SimpleShadow,
    0xB6EC1A51: SimpleSound,
    0xF3BC4EE8: SimpleSoundPhaseResponder,
    0x3ABCFF68: SkinSwap,
    0x5112A065: Skybox,
    0x7A6ED813: SlideShow,
    0x1D4532DB: SnapToPath,
    0xBC5EB9D5: SniperPoint,
    0xFDD83489: Sound,
    0x512A3EE4: SoundFilterModifier,
    0x99DC9C6E: SoundLevelMeterPhaseDriver,
    0xD3FD952C: SoundPitchModifier,
    0xC03CD39D: SoundVolumeModifier,
    0xEA30E0B1: SpawnPoint,
    0x2C4F2D31: SplineMotion,
    0xC6C04116: SplineMotionPhaseResponder,
    0x57153AA4: StaticCollision,
    0x02C9D30B: Steering,
    0xBFF963D2: StreamedMovie,
    0x57AB06B5: SubtitleSequence,
    0x0BE7FC29: SurfaceControl,
    0x4EEBAAD3: SurfaceGenerator,
    0xBDE4AB05: TakeDamage,
    0xD645278A: TemplateManager,
    0x2BA4912D: Terrain,
    0x2D0F036C: TerrainAlignment,
    0x38ACAAF1: TextPane,
    0x3EC5D79A: TimeDilation,
    0xF442A668: TimeKeyframe,
    0x9E8A4940: Timer,
    0x18B96D29: TimerAnimationGridParamProvider,
    0xEF5E0348: TimerProgression,
    0x046FAD23: TimerSequence,
    0xA623AFA1: TimerSequencePhaseResponder,
    0xD81587E0: TimerStopwatch,
    0x91F22DCF: Tippy,
    0x067598BE: ToneData,
    0x4ADC88B7: ToneSelectorHint,
    0x49D039CD: ToneSelectorMIDI,
    0xD0E99272: ToneSelectorScriptDriven,
    0x8F4A3A35: ToneSelectorSequence,
    0xDDEA916D: Tonemap,
    0x1A4117AB: Touch,
    0x502506D6: TouchSet,
    0x97E65DDD: TouchableTrigger,
    0xA9584C89: TriggerDamage,
    0xFD46F49E: TriggerDeathFall,
    0xBD4CFA2F: TriggerForce,
    0x91F73D69: TriggerInhabitant,
    0xC49D730E: TriggerLogic,
    0x780E031E: TriggerProgressionVolume,
    0x013DAAAC: UIButton,
    0xB35B0375: UICamera,
    0x5445F685: UIListView,
    0x07EDF6B2: UIMenu,
    0x00C80DDC: UIProxy,
    0x2376DE64: UIRelay,
    0x5F0FA37C: UISlider,
    0x3CFFFC01: UIWidget,
    0x6302BBB3: UVTransform,
    0x24D9D323: VoiceEffect,
    0x1B9CD84F: VolumetricFog,
    0x84FB5798: VolumetricFogHint,
    0xAFFE9CF9: VolumetricFogRegion,
    0xDF95AC1A: VolumetricFogRegionTransition,
    0xE262F4AF: WanderPoint,
    0x23C5DFF4: WaterRenderVolume,
    0xD898656D: Waypoint,
    0x53744D89: WindWaker,
    0x564DEE0F: WorldTransition,
}


@functools.cache
def get_object(four_cc: int) -> type[BaseProperty]:
    return _FOUR_CC_MAPPING[four_cc]
