# Generated by tools/asset_reference_files.py

from retro_data_structures.references.reference_database import echoes_db as _echoes_db

_db = _echoes_db()

CONTROLLER_TRANSPORT_MREA = _db[0x11e50bc6]
MAIN_ENERGY_CONTROLLER_MREA = _db[0x2a01334]
SANCTUM_ACCESS_MREA = _db[0xcbad889b]
SANCTUM_MREA = _db[0xd7c3b839]
SKY_TEMPLE_ENERGY_CONTROLLER_MREA = _db[0x7b4afa6f]
TEMPLE_SANCTUARY_MREA = _db[0xa2cb7e32]
TEMPLE_TRANSPORT_A_MREA = _db[0x185b40f0]
TEMPLE_TRANSPORT_B_MREA = _db[0x8f01b104]
TEMPLE_TRANSPORT_C_MREA = _db[0x9860cbb0]
TRANSPORT_A_ACCESS_MREA = _db[0xe79aafae]
TRANSPORT_B_ACCESS_MREA = _db[0xfeb7bd27]
TRANSPORT_C_ACCESS_MREA = _db[0x1a4ddcc0]
