# Generated by tools/asset_reference_files.py

from retro_data_structures.references.reference_database import echoes_db as _echoes_db

_db = _echoes_db()

AGON_WASTES_MLVL = _db[0x42b935e4]
FRONTEND_MLVL = _db[0x69802220]
GREAT_TEMPLE_MLVL = _db[0x863fcd72]
M01_SIDEHOPPERSTATION_MLVL = _db[0xa50a80cc]
M02_SPIRES_MLVL = _db[0xae171602]
M03_CROSSFIRECHAOS_MLVL = _db[0xe3b0c703]
M04_PIPELINE_MLVL = _db[0x233e42be]
M05_SPIDERCOMPLEX_MLVL = _db[0x406add7f]
M06_SHOOTINGGALLERY_MLVL = _db[0x7e19ed26]
SANCTUARY_FORTRESS_MLVL = _db[0x1baa96c2]
TEMPLE_GROUNDS_MLVL = _db[0x3bfa3eff]
TORVUS_BOG_MLVL = _db[0x3dfd2249]
